# 35 new member downloads (5 already exist). pdf = generator key in bulk_pdfs.py
D = lambda slug, emoji, sort, title, excerpt, file, pdf, steps, tip: {
    "slug": slug, "emoji": emoji, "sort": sort, "title": title, "excerpt": excerpt,
    "file": file, "pdf": pdf, "steps": steps, "tip": tip,
}

DOWNLOADS = [
    D("subtraction-to-10", "➖", 97, "Subtraction Practice: Numbers to 10",
      "40 subtraction problems within 10. The follow-up to our addition pack.",
      "worksheets/subtraction-to-10.pdf", "math_sub",
      ["Print A4, one page a day (20 problems, about 5 minutes)",
       "Use the 'count up' trick for hard ones: for 9 - 7, count 7...8, 9 — that is 2",
       "Circle mistakes and redo them first the next day"],
      "Pair with our Subtraction Without Tears guide for the concrete-to-abstract method."),
    D("addition-to-20", "🔟", 98, "Addition Practice: Numbers to 20",
      "40 problems within 20. For kids who mastered addition to 10.",
      "worksheets/addition-to-20.pdf", "math_add20",
      ["Print A4, one page a day",
       "Teach making-ten: 8 + 5 = 8 + 2 + 3",
       "Time them when ready — speed is the final level"],
      "If they struggle, go back to number bonds to 10 first — the foundation matters more than the level."),
    D("number-bonds-10", "🔗", 99, "Number Bonds to 10",
      "All pairs that make 10, as fill-in-the-blank rainbows and ten-frames.",
      "worksheets/number-bonds-10.pdf", "bonds",
      ["Do one page a day — 5 minutes",
       "Say each bond out loud: '7 and 3 make 10'",
       "Test speed when confident: all pairs in under 30 seconds"],
      "These pairs are the secret behind fast mental math — do not rush past them."),
    D("greater-less-than", "⚖️", 100, "Greater Than / Less Than",
      "Compare numbers to 20 with the hungry crocodile mouth. 24 problems.",
      "worksheets/greater-less-than.pdf", "compare",
      ["Teach the trick: the open mouth eats the BIGGER number",
       "Draw the mouth between each pair, then read it: '7 is greater than 4'",
       "Start with numbers to 10, then try to 20"],
      "Say it out loud every time — the language IS the concept."),
    D("counting-to-20", "🔢", 101, "Count & Write: Numbers to 20",
      "Count the shapes, write the number. The bridge from 10 to 20.",
      "worksheets/counting-to-20.pdf", "count20",
      ["Point and count each shape one by one — no skipping",
       "Write the number in the box, then color the shapes",
       "Group in tens: '10 and 3 more is 13'"],
      "Teens are tricky because English names are irregular — 'thirteen' hides 'three'. Count slowly."),
    D("tens-frames-10", "🟦", 102, "Ten-Frames Practice",
      "Fill ten-frames to see numbers as parts of 10. 3 pages.",
      "worksheets/tens-frames-10.pdf", "tenframes",
      ["Color the frame to show each number — always fill left to right, top row first",
       "Ask: 'How many more to make 10?'",
       "Do one page a day"],
      "Ten-frames build the 'see 7 as 10-minus-3' instinct that powers mental math."),
    D("alphabet-tracing-a-m", "🔤", 103, "Alphabet Tracing: A–M",
      "Big traceable capital letters A through M, with picture cues.",
      "worksheets/alphabet-tracing-a-m.pdf", "trace_am",
      ["Finger-trace first, then crayon-trace",
       "Say the letter name AND sound: 'B — buh'",
       "One letter a day is plenty"],
      "Capitals first — they are simpler shapes. Lowercase comes later."),
    D("alphabet-tracing-n-z", "🔡", 104, "Alphabet Tracing: N–Z",
      "Big traceable capital letters N through Z, with picture cues.",
      "worksheets/alphabet-tracing-n-z.pdf", "trace_nz",
      ["Finger-trace first, then crayon-trace",
       "Say the letter name AND sound",
       "When done: mix A–Z cards and name them fast"],
      "Finish both packs, then play alphabet Go Fish with the letters."),
    D("shape-tracing", "⭐", 105, "Shape Tracing Pack",
      "Trace circles, squares, triangles and more — pre-writing shape control.",
      "worksheets/shape-tracing.pdf", "trace_shapes",
      ["Trace each shape 3 times with a finger, then with a crayon",
       "Name each shape out loud while tracing",
       "Try drawing one freehand after tracing"],
      "Shape tracing builds the hand control that letters need later."),
    D("word-families", "📝", 106, "Word Families Flashcards",
      "48 cards across 8 families: -at, -an, -ot, -op, -ug, -ed, -in, -ake.",
      "worksheets/word-families.pdf", "fc_wordfam",
      ["Cut the cards, pick one family at a time",
       "Change the first letter: c-at, h-at, m-at — hear the pattern",
       "Read the whole family fast when confident"],
      "Word families are blending practice in disguise — the best phonics workout."),
    D("rhyming-pairs", "🎵", 107, "Rhyming Pairs Matching Cards",
      "24 pairs that rhyme. Match them, then make up silly rhymes.",
      "worksheets/rhyming-pairs.pdf", "fc_rhyme",
      ["Cut out all cards, lay face up, find the rhyming pairs",
       "Say each pair out loud — hearing the rhyme is the point",
       "Memory version: lay face down, flip two at a time"],
      "Nonsense rhymes count! 'Dog... zog!' builds the same skill."),
    D("addition-flashcards", "🃏", 108, "Addition Flashcards: to 10",
      "36 addition facts as cut-out flashcards for daily drills.",
      "worksheets/addition-flashcards.pdf", "fc_add",
      ["Cut along dashed lines — cardstock recommended",
       "2-second rule: instant = keep, hesitate = back in the pile",
       "5 new facts a week, review old ones daily"],
      "Speed comes from the pile shrinking — celebrate every card retired."),
    D("subtraction-flashcards", "🎴", 109, "Subtraction Flashcards: to 10",
      "36 subtraction facts as cut-out flashcards.",
      "worksheets/subtraction-flashcards.pdf", "fc_sub",
      ["Cut along dashed lines",
       "2-second rule: instant = keep, hesitate = back in the pile",
       "Mix with addition cards when both are solid"],
      "Teach the count-up trick for the stubborn ones: 12 - 9 → '9...10, 11, 12 — 3!'"),
    D("animal-flashcards", "🦁", 110, "Animal Flashcards",
      "24 animals with emoji and names — vocabulary plus sorting games.",
      "worksheets/animal-flashcards.pdf", "fc_animals",
      ["Name each animal, then sort: farm / wild / ocean",
       "'Which is biggest? Which can fly?' — sorting questions",
       "Pick 3 and make up a story together"],
      "Sorting the cards is classification practice — early science thinking."),
    D("color-flashcards", "🎨", 111, "Color Flashcards",
      "12 colors as big swatch cards — plus shades (light blue, dark green).",
      "worksheets/color-flashcards.pdf", "fc_colors",
      ["Hold up a card — race to find something that color in the room",
       "Sort the shades: light to dark",
       "Mix paint to match a card — color science"],
      "Shades (light/dark) are the level-up — most packs skip them."),
    D("emotion-flashcards", "😊", 112, "Emotions Flashcards",
      "16 feelings with faces — the daily check-in deck.",
      "worksheets/emotion-flashcards.pdf", "fc_emotions",
      ["Morning check-in: 'Which face are you today?'",
       "Act one out — family guesses",
       "Pair with our Name It to Tame It guide"],
      "A child who can point to 'frustrated' does not need to throw the block."),
    D("dot-to-dot-fun", "✏️", 113, "Dot-to-Dot: 1 to 20",
      "4 dot-to-dot puzzles — connect in order, reveal the picture, then color it.",
      "worksheets/dot-to-dot-fun.pdf", "dotdot",
      ["Connect the dots in NUMBER order — say each number out loud",
       "Do not peek at the answer — the reveal is the reward",
       "Color the picture when done"],
      "Saying numbers in order while connecting builds sequence fluency."),
    D("easy-mazes", "🌀", 114, "Easy Mazes: 6 Puzzles",
      "6 mazes from simple to tricky — pencil control plus planning.",
      "worksheets/easy-mazes.pdf", "mazes",
      ["Trace the path with a finger FIRST, then with a pencil",
       "'Plan before you draw' — looking ahead is the skill",
       "Time the last maze and beat the record"],
      "Finger-first prevents the scribble-and-hope approach."),
    D("color-by-number", "🖍️", 115, "Color by Number: 3 Pictures",
      "3 pictures that appear as you color by the number key.",
      "worksheets/color-by-number.pdf", "cbn",
      ["Match each number to the color key — check twice",
       "Color one section at a time, stay inside the lines",
       "The picture reveals itself — do not peek"],
      "Number recognition + fine motor + patience, all in one."),
    D("pattern-complete", "🔶", 116, "Complete the Pattern",
      "24 pattern rows: AB, ABB, ABC — draw what comes next.",
      "worksheets/pattern-complete.pdf", "patterns",
      ["Look at the row, find the repeating unit",
       "Say it out loud: 'red, blue, red, blue...'",
       "Draw the next 3 — then invent your own row"],
      "Saying the pattern aloud is what makes the rule click."),
    D("cutting-practice", "✂️", 117, "Cutting Practice: Lines & Shapes",
      "Straight, zigzag, wavy, spiral, and shape outlines to cut.",
      "worksheets/cutting-practice.pdf", "cutting",
      ["Start with straight lines — snip, slide, snip",
       "Thumbs up on top! — the grip cue that fixes most problems",
       "Curves last — they are the boss level"],
      "Cutting order: straight → zigzag → wave → spiral → shapes."),
    D("symmetry-draw", "🦋", 118, "Symmetry Drawing",
      "Half-drawn butterflies, faces, and houses — complete the mirror side.",
      "worksheets/symmetry-draw.pdf", "symmetry",
      ["Fold the paper on the dotted line first — see the mirror idea",
       "Draw the missing half to match",
       "Color both sides the same — check the match"],
      "Symmetry is geometry you can see — and it is beautiful."),
    D("telling-time-practice", "🕐", 119, "Telling Time Practice",
      "12 clock faces: draw the hands for o'clock and half past.",
      "worksheets/telling-time-practice.pdf", "clocks",
      ["Read the time words, draw the hands — short hand FIRST",
       "O'clock: long hand on 12. Half past: long hand on 6",
       "Check with a real clock afterward"],
      "Short hand first, always — it is the one that matters most."),
    D("money-coins", "🪙", 120, "Counting Coins",
      "Identify pennies, nickels, dimes, quarters — then count real amounts.",
      "worksheets/money-coins.pdf", "coins",
      ["Name each coin and its value — size does NOT match value",
       "Count the coins in each piggy bank by skip-counting",
       "Set up the toy store game from our Money Basics guide"],
      "Real coins beat pictures — use the real thing alongside this pack."),
    D("chore-chart", "🧹", 121, "Chore Chart: Weekly",
      "A printable weekly chart with 8 age-appropriate chores and star boxes.",
      "worksheets/chore-chart.pdf", "chart_chore",
      ["Print and hang at kid height — let them pick 3 daily chores",
       "Star for each done — no stars removed, ever",
       "Sunday review: count stars together, celebrate the week"],
      "Stars are earned, never taken away — the chart is encouragement, not currency."),
    D("reward-chart", "⭐", 122, "Sticker Reward Chart: 4 Weeks",
      "A 4-week sticker chart for any goal — with milestone celebrations.",
      "worksheets/reward-chart.pdf", "chart_reward",
      ["Pick ONE goal together — specific and small",
       "Sticker immediately when earned — delay kills motivation",
       "Milestone at weeks 1, 2, 4 — small celebrations"],
      "One goal at a time. Retire the chart when the habit sticks — that is success."),
    D("weather-tracker", "🌤️", 123, "Weather Tracker: 7 Days",
      "A week of weather watching: clouds, temperature, rain — with drawing boxes.",
      "worksheets/weather-tracker.pdf", "chart_weather",
      ["Check the sky each morning — same time daily",
       "Draw the clouds, write the temperature, mark rain",
       "Sunday: 'What was the pattern this week?'"],
      "Pair with our Weather Watchers guide and the bottle rain gauge."),
    D("feelings-journal", "💭", 124, "Feelings Journal: Daily Check-in",
      "A daily page: pick the feeling, draw it, write or dictate why.",
      "worksheets/feelings-journal.pdf", "journal_feelings",
      ["Print 7 copies — one week",
       "Morning or bedtime — same time daily builds the habit",
       "No wrong answers — 'silly' is a valid feeling"],
      "Review the week together: 'You felt proud three times — what made those days special?'"),
    D("gratitude-journal", "🙏", 125, "Gratitude Journal",
      "Daily prompts: one good thing, one kind person, one thing in nature.",
      "worksheets/gratitude-journal.pdf", "journal_gratitude",
      ["Print 7 copies — one week",
       "Adults fill one too — modeling is everything",
       "Read Friday's entries aloud at dinner"],
      "Specific beats generic: 'the crunchy apple at lunch' beats 'food'."),
    D("planting-log", "🌱", 126, "Planting Log: Bean Diary",
      "A 14-day observation log for the bean-in-a-cup project.",
      "worksheets/planting-log.pdf", "log_plant",
      ["Print 2 weeks' worth — observe and draw daily",
       "Measure the sprout with a ruler — write the number",
       "Pair with our Growing Beans guide"],
      "The drawing IS the data — scientists sketch. So can they."),
    D("science-journal", "🔬", 127, "Science Journal: Experiment Sheets",
      "The universal lab sheet: question, guess, test, result. Print as many as needed.",
      "worksheets/science-journal.pdf", "journal_science",
      ["One sheet per experiment",
       "ALWAYS write the guess before testing — the guess is the science",
       "Draw the result — then answer 'what surprised me?'"],
      "Keep finished sheets in a folder — their first lab notebook."),
    D("weekly-schedule", "🗓️", 128, "Weekly Visual Schedule",
      "A picture-based weekly schedule — morning, afternoon, evening blocks.",
      "worksheets/weekly-schedule.pdf", "schedule",
      ["Fill in the repeating anchors together: meals, school, bedtime",
       "Draw or stick pictures for each block",
       "Hang where mornings happen — point to it instead of nagging"],
      "Kids argue less with a schedule than with a parent. Let the paper be the boss."),
    D("story-sequence", "🎬", 129, "Story Sequencing Cards",
      "4-panel strips: draw first, next, then, last — for any story.",
      "worksheets/story-sequence.pdf", "storyseq",
      ["Retell a familiar book in 4 pictures — one per panel",
       "Then invent: draw YOUR story in 4 panels and tell it",
       "Number each panel — order is the lesson"],
      "Sequencing is the skeleton of storytelling — and of reading comprehension."),
    D("all-about-me", "🌟", 130, "All About Me Poster",
      "A fill-in poster: favorites, family, dreams — with drawing boxes.",
      "worksheets/all-about-me.pdf", "allaboutme",
      ["Fill it together — scribes welcome for little ones",
       "Draw in every box — no blank spaces",
       "Hang it up — then redo it in 6 months and compare"],
      "The 6-month comparison is the real treasure — growth you can see."),
    D("nature-scavenger-hunt", "🍂", 131, "Nature Scavenger Hunt",
      "A checkbox hunt: 16 things to find outside, from smooth stones to bird sounds.",
      "worksheets/nature-scavenger-hunt.pdf", "scavenger",
      ["Print and bring a bag for treasures",
       "Check off as you find — no rushing, 30 minutes minimum",
       "Sort the treasures at home: by color, size, or texture"],
      "Pair with our 5-Senses Walk guide for the full outdoor session."),
]
