# Member articles, batch 2: Art (8) + Habits & Life Skills (8) + Social-Emotional (8)
MEMBER_2 = [
    {
        "slug": "process-art", "emoji": "🖌️", "sort": 60,
        "title": "Process Art: It's About the Doing, Not the Fridge-Worthy Result",
        "excerpt": "Stop asking 'what is it?' The mindset shift that unlocks real creativity.",
        "intro": "Process art = art where the experience matters more than the product. Kids who are freed from 'making it look good' experiment more — and experiment is where creativity lives.",
        "sections": [
            ("The mindset shift", [
                "Replace 'What is it?' with 'Tell me about what you did' — process questions, not product questions",
                "Display the messy ones too — or display nothing and just enjoy",
                "Never 'fix' their art. Your correction teaches them their instincts are wrong.",
            ]),
            ("5 process art starters", [
                "Marble rolling: tray + paper + paint-covered marbles — tilt and watch",
                "Salad spinner art: paper + drops of paint + spin",
                "Ice painting: freeze paint in cubes, slide on paper as they melt",
                "Bubble wrap stamping: paint on bubble wrap, press paper on top",
                "Nature brushes: paint with leaves, sticks, flowers instead of brushes",
            ]),
            ("Setup that saves sanity", [
                "The art smock lives by the supplies — non-negotiable uniform",
                "A plastic tablecloth defines the art zone; everything outside it stays clean",
                "Washable everything. The good paint is not worth the stress.",
            ]),
        ],
        "try": ["Try marble rolling this week", "Ask 'tell me about it' instead of 'what is it' for 7 days", "Set up a permanent art zone"],
        "close": "The fridge is for groceries. Art is for the child.",
    },
    {
        "slug": "drawing-basics", "emoji": "✏️", "sort": 61,
        "title": "Drawing Basics: From Scribbles to People With Fingers",
        "excerpt": "Every stage is normal. What to expect when, and how to nudge without pushing.",
        "intro": "Drawing develops in predictable stages. Knowing them stops you from worrying — and shows you exactly how to help at each step.",
        "sections": [
            ("The stages", [
                "Scribble (2–3): random marks — the joy is in the movement. Provide big paper.",
                "Shapes (3–4): circles, lines, crosses appear. Name them: 'You drew a circle!'",
                "Tadpole people (4–5): big head, stick limbs — completely normal and wonderful",
                "Detailed people (5–6): fingers, clothes, backgrounds appear — add prompts, not corrections",
            ]),
            ("How to nudge forward", [
                "Draw WITH them, not FOR them — side-by-side modeling",
                "'Can you add the sunshine?' — invitations, not instructions",
                "Copy games: you draw a shape, they copy — builds control",
                "Our symmetry-drawing pack is perfect practice for ages 5–6",
            ]),
            ("What NOT to do", [
                "Never draw ON their paper to 'show them' — it reads as 'yours is wrong'",
                "Do not compare to other kids' drawings",
                "Keep every stage's drawings — the progression is the treasure",
            ]),
        ],
        "try": ["Draw side-by-side for 15 minutes this week", "Try one copy-game session", "Date and save 3 drawings"],
        "close": "Every artist was once a scribbler. Protect the scribble.",
    },
    {
        "slug": "playdough-recipe", "emoji": "🟠", "sort": 62,
        "title": "The Best Playdough Recipe (and 10 Things to Make)",
        "excerpt": "Five minutes, one pot, months of play. Plus the challenges that build hand strength.",
        "intro": "Homemade playdough is softer, cheaper, and more satisfying than store-bought. This no-fail recipe plus 10 challenges = weeks of fine-motor workouts.",
        "sections": [
            ("The recipe", [
                "1 cup flour, 1/4 cup salt, 2 tsp cream of tartar, 1 cup water, 1 tbsp oil",
                "Stir over medium heat until it balls up (2–3 min) — it looks wrong until it suddenly looks right",
                "Knead with food coloring once cool. Lasts months in a zip bag.",
            ]),
            ("10 challenges", [
                "Roll 5 snakes from short to long — order them",
                "Make the letters of your name",
                "Build a pizza: flatten, add topping balls, 'bake' it",
                "Poke 10 holes with a pencil — then fill each with a bead",
                "Make 3 animals and give them a story",
                "Copy a shape from a card",
                "Make the biggest ball, then the tiniest",
                "Press leaves in for texture prints",
                "Build a tower as tall as your hand",
                "Hide a coin inside — sibling has to find it by squishing",
            ]),
            ("Why it matters", [
                "Squeezing builds the exact hand muscles writing needs",
                "It is calming — the rare activity that is both workout and wind-down",
            ]),
        ],
        "try": ["Make one batch this weekend", "Try 3 challenges this week", "Store it in a zip bag — test longevity"],
        "close": "Strong hands write well. Playdough builds strong hands.",
    },
    {
        "slug": "collage-art", "emoji": "✂️", "sort": 63,
        "title": "Collage Art: Scissors, Glue, and Old Magazines",
        "excerpt": "Cutting practice disguised as art. The setup that makes collage actually fun.",
        "intro": "Collage is cutting practice, decision-making, and composition — all while feeling like pure play. The secret is in the material prep.",
        "sections": [
            ("Prep the materials", [
                "Pre-cut a pile of interesting bits: colors, textures, faces, animals — kids choose, not cut, at first",
                "Child-safe scissors + glue stick (less mess than liquid glue)",
                "A big background paper — small paper frustrates",
            ]),
            ("The progression", [
                "Free collage: glue anything anywhere — pure joy",
                "Themed: 'Make an animal' / 'Make a rainy day' — gentle constraint",
                "Shape collage: fill a big drawn shape with cut pieces — mosaic thinking",
            ]),
            ("Cutting practice built in", [
                "Our cutting-practice pack has the lines to master: straight, zigzag, wave, spiral",
                "Cutting order: snipping → straight lines → curves → shapes",
                "Thumbs up on top! — the one cue that fixes most grip problems",
            ]),
        ],
        "try": ["Prep a collage box this weekend", "Do one free collage session", "Print the cutting-practice pack"],
        "close": "Scissors are a skill. Collage is the practice that does not feel like practice.",
    },
    {
        "slug": "painting-no-mess", "emoji": "🎨", "sort": 64,
        "title": "Painting Without the Mess: 5 Contained Techniques",
        "excerpt": "All the joy, none of the couch stains. Five painting methods that stay where they should.",
        "intro": "You avoid painting because of the mess. These five techniques contain the chaos — so you say yes more often.",
        "sections": [
            ("The 5 techniques", [
                "Bag painting: paint blobs in a sealed zip bag — squish with fingers, zero cleanup",
                "Q-tip painting: tiny dots only — pointillism for preschoolers, naturally contained",
                "Ice painting: frozen paint cubes melt into art — cold slows everything down",
                "Roller painting: small brayer rollers cover big paper fast — satisfying, hard to spill",
                "Tape resist: tape shapes on paper, paint over, peel — the reveal is magic",
            ]),
            ("The setup rules", [
                "Smock on, tablecloth down, water cup with a LID",
                "One color at a time for under-4s — brown happens when colors mix unsupervised",
                "Washable tempera only. The 'good' paint is never worth it at this age.",
            ]),
        ],
        "try": ["Try bag painting this week — easiest start", "Do tape-resist for the big reveal moment", "Set up the permanent paint zone"],
        "close": "Say yes to paint. Just contain it first.",
    },
    {
        "slug": "recycled-crafts", "emoji": "♻️", "sort": 65,
        "title": "Trash to Treasure: 8 Crafts From the Recycling Bin",
        "excerpt": "Cardboard, caps, and tubes — the best craft supplies are the ones you were throwing away.",
        "intro": "Recycled crafts teach creativity's core lesson: see possibility in ordinary things. Eight projects, zero purchases.",
        "sections": [
            ("The projects", [
                "Tube binoculars: 2 toilet rolls + string — instant explorer gear",
                "Box city: one big box becomes a house, shop, or rocket (crayons required)",
                "Cap mosaics: bottle caps glued into patterns on cardboard",
                "Egg carton caterpillars: cut, paint, pipe-cleaner antennae",
                "Cardboard guitars: box + rubber bands — then our kitchen band plays",
                "Tube marble run: tape rolls to the wall, drop pom-poms through",
                "Milk jug watering can: poke holes in the cap",
                "Newspaper hats: fold, decorate, parade",
            ]),
            ("The craft box", [
                "Keep one box for 'craft trash': tubes, caps, boxes, ribbons",
                "When it is full, craft. When it is empty, collect. The rhythm sustains itself.",
            ]),
        ],
        "try": ["Start the craft-trash box today", "Build tube binoculars this weekend", "Make one box city together"],
        "close": "Creativity is seeing a rocket in a box.",
    },
    {
        "slug": "music-making", "emoji": "🥁", "sort": 66,
        "title": "Make Instruments From Kitchen Junk",
        "excerpt": "Shakers, drums, and guitars from things you own. Then: the family band concert.",
        "intro": "Making the instrument is half the music lesson. Build these in 20 minutes, then hold a concert — rhythm, listening, and pure joy.",
        "sections": [
            ("The instruments", [
                "Rice shaker: sealed jar + rice — compare rice vs. beans vs. pasta sounds",
                "Pot drum: upside-down pot + wooden spoon — different pots, different pitches",
                "Box guitar: tissue box + rubber bands — tight vs. loose bands",
                "Paper plate tambourine: 2 plates + dried beans stapled between (adults staple)",
                "Straw panpipes: cut straws to different lengths, tape together — shorter = higher!",
            ]),
            ("The concert", [
                "One conductor (rotate!), everyone follows the beat",
                "Play along to a favorite song — keeping the beat is the skill",
                "Record it. Play it for grandparents. Applause is fuel.",
            ]),
            ("The science hiding inside", [
                "'Why does the short straw sound higher?' — let them guess before you explain",
                "Fill jars with different water levels and tap — a water xylophone",
            ]),
        ],
        "try": ["Build rice shakers tonight", "Hold a 10-minute family concert", "Try the water xylophone this weekend"],
        "close": "Musicians are made, not born. Start with a jar of rice.",
    },
    {
        "slug": "puppet-shows", "emoji": "🧦", "sort": 67,
        "title": "Sock Puppets and Shoebox Theaters",
        "excerpt": "Storytelling, empathy, and voice practice hiding inside a sock with button eyes.",
        "intro": "Puppets let shy kids speak boldly — it is the puppet talking, not them. Build a cast in an afternoon, then let stories happen.",
        "sections": [
            ("Build the cast", [
                "Sock puppets: sock + button eyes (glue) + yarn hair — 5 minutes each",
                "Paper bag puppets: draw the face, the fold is the mouth — it TALKS",
                "Stick puppets: draw characters, tape to straws — easiest for under-4s",
            ]),
            ("The theater", [
                "Shoebox stage: cut a window in the box, puppets perform from below",
                "Couch-back theater: kneel behind the couch, puppets pop up",
                "Curtain call: every show ends with bows — ritual matters",
            ]),
            ("Why it works", [
                "Kids rehearse social situations through puppets: the puppet apologizes, shares, feels scared",
                "Retell familiar stories first (Three Little Pigs), then invent",
                "Record a show — watching themselves builds narrative awareness",
            ]),
        ],
        "try": ["Make 2 sock puppets this weekend", "Retell one familiar story with puppets", "Build the shoebox theater"],
        "close": "Behind a puppet, every child is brave.",
    },
    {
        "slug": "morning-chart", "emoji": "📋", "sort": 68,
        "title": "The Morning Routine Chart That Runs Itself",
        "excerpt": "Stop being the alarm clock. A picture chart that moves the nagging off your plate.",
        "intro": "Kids cannot hold a 6-step sequence in working memory — but they can follow pictures. A visual chart turns you from nag into consultant.",
        "sections": [
            ("Build the chart", [
                "Photograph YOUR child doing each step: wake, bathroom, dress, breakfast, teeth, shoes, backpack",
                "Print small, stick in order on a strip — velcro dots let them flip each 'done'",
                "Hang at their eye level where the morning happens",
            ]),
            ("Launch it", [
                "Walk through it together twice — then hand over control",
                "Your only phrase: 'Check your chart.' Say nothing else. This is the hard part.",
                "Celebrate the first fully independent morning like a graduation",
            ]),
            ("Keep it alive", [
                "Update photos every few months — old photos get ignored",
                "Add a fun step at the end: 'hug!' or 'joke of the day'",
                "If mornings still stall, the chart is too long — cut to 5 steps max",
            ]),
        ],
        "try": ["Photograph the 6 steps this weekend", "Build and hang the chart", "Use ONLY 'check your chart' for one week"],
        "close": "The chart nags so you do not have to.",
    },
    {
        "slug": "brushing-teeth", "emoji": "🪥", "sort": 69,
        "title": "Brushing Teeth Without a Fight",
        "excerpt": "Two minutes feels like forever at age 4. The songs, timers, and choices that fix it.",
        "intro": "Tooth-brushing battles are about duration and control. Fix both: make the time pass enjoyably and hand them choices.",
        "sections": [
            ("Make 2 minutes fun", [
                "The song rule: brush for one whole song — let them pick it",
                "Electric toothbrush with a built-in timer — the buzz does the nagging",
                "Brush together: they copy your motions in the mirror",
            ]),
            ("Give control", [
                "Two toothbrushes to choose from, two toothpaste flavors",
                "'You do the front, I do the back' — teamwork beats takeover",
                "A sticker on the chart for each brush — visible streaks motivate",
            ]),
            ("Teach the technique simply", [
                "'Tickle the teeth' — small circles, not sawing",
                "'Say ahh' for the back teeth — make it a game",
                "Spit, do not rinse — the fluoride needs to stay (ask your dentist)",
            ]),
        ],
        "try": ["Start the one-song rule tonight", "Let them pick a new toothbrush", "Add brushing to the morning chart"],
        "close": "Two minutes, twice a day, zero fights. Systems beat willpower.",
    },
    {
        "slug": "table-manners", "emoji": "🍽️", "sort": 70,
        "title": "Table Manners in 5 Tiny Lessons",
        "excerpt": "Not etiquette school — just the five habits that make family dinner pleasant.",
        "intro": "Table manners at 3–6 are not about which fork. They are five tiny habits, taught one at a time, modeled always.",
        "sections": [
            ("The five lessons (one per month is fine)", [
                "**Stay seated**: 'Chairs are for sitting' — a wobble cushion helps wigglers",
                "**Chew with mouth closed**: model exaggeratedly; praise when they do",
                "**Please and thank you**: require it for seconds — natural practice, 3x daily",
                "**Napkin on lap**: make it step 1 of sitting down — ritual beats reminder",
                "**Excuse me**: teach the phrase for leaving and for burps — kids love having the 'right' word",
            ]),
            ("How to teach without lecturing", [
                "Model everything — they copy what you do, not what you say",
                "Praise the specific behavior: 'You remembered your napkin!'",
                "One gentle reminder, then natural consequence: 'Food stays at the table'",
            ]),
        ],
        "try": ["Pick ONE lesson for this month", "Model it exaggeratedly for a week", "Praise it specifically 3x daily"],
        "close": "Manners are habits, not knowledge. One habit at a time.",
    },
    {
        "slug": "packing-backpack", "emoji": "🎒", "sort": 71,
        "title": "Pack Your Own Backpack: The Evening Checklist",
        "excerpt": "Responsibility is packable. The 5-item checklist that ends forgotten lunches.",
        "intro": "Packing their own bag teaches planning, memory, and ownership. A 5-item picture checklist makes it doable at 4.",
        "sections": [
            ("The 5-item checklist", [
                "Water bottle (filled)",
                "Lunchbox / snack",
                "Folder or papers",
                "Weather gear (jacket? hat?)",
                "One comfort item / show-and-tell",
                "Photo each item, print as a strip, hang by the door",
            ]),
            ("Teach the routine", [
                "Do it together for 2 weeks — you point, they pack",
                "Then fade: 'Check your strip' replaces your reminders",
                "Let natural consequences teach: forgotten snack = hungry afternoon (once is enough)",
            ]),
            ("Level up", [
                "Sunday reset: empty the whole bag, toss trash, restock together",
                "Let them choose the backpack — ownership starts with choosing",
            ]),
        ],
        "try": ["Photograph the 5 items this weekend", "Pack together for 2 weeks", "Do the first Sunday reset"],
        "close": "Forgetting is the teacher. Let it teach.",
    },
    {
        "slug": "cleanup-games", "emoji": "🧸", "sort": 72,
        "title": "Clean Up in 10 Minutes: 5 Games That Work",
        "excerpt": "'Clean your room' fails. Games succeed. Five that actually get toys in bins.",
        "intro": "'Clean up' is overwhelming — it is 50 micro-decisions. Games shrink it to one fun rule at a time.",
        "sections": [
            ("The 5 games", [
                "**Beat the song**: one cleanup song — everything away before it ends",
                "**Color round**: 'Only red toys! Go!' — then blue, then yellow",
                "**Basketball bins**: toss soft toys into bins from a line — score points",
                "**Toy rescue**: 'The toys are lost! Rescue them to their homes!'",
                "**10-second tidy**: set a timer, frantic 10 seconds, rest, repeat 5x",
            ]),
            ("Set up for success", [
                "Bins labeled with PICTURES, not words — every toy has a home",
                "Fewer toys out = faster cleanup. Rotate the rest monthly.",
                "Clean up BEFORE the next activity, every time — the sequence matters",
                "Join in for the first 2 minutes, then fade — momentum is contagious",
            ]),
        ],
        "try": ["Label bins with pictures this weekend", "Try beat-the-song tonight", "Reduce visible toys by half"],
        "close": "Tidy is a game before it is a habit.",
    },
    {
        "slug": "tying-shoes", "emoji": "👟", "sort": 73,
        "title": "Tying Shoes: The Two-Loop Method That Clicks",
        "excerpt": "Forget the rabbit-around-the-tree. Bunny ears first, then the grown-up way.",
        "intro": "Shoe-tying is the hardest fine-motor task of early childhood. The two-loop (bunny ears) method has fewer steps — start there.",
        "sections": [
            ("Bunny ears method", [
                "Make a loop with each lace — 'two bunny ears'",
                "Cross the ears and pull one through — 'the bunny hops through the hole'",
                "Pull both ears — done!",
                "Practice on a shoe OFF the foot first, laces facing them",
            ]),
            ("Practice setup", [
                "A practice board: lace a cardboard 'shoe' they can hold in their lap",
                "5 minutes a day beats a 30-minute frustrated session",
                "Celebrate the first solo tie enormously — then expect it to take 2 weeks to stick",
            ]),
            ("When to start", [
                "Readiness signs: can do buttons, uses scissors well — usually age 5–6",
                "No rush: velcro exists for a reason. Readiness beats schedule.",
            ]),
        ],
        "try": ["Make a cardboard practice shoe", "Practice 5 min daily for 2 weeks", "Learn bunny ears before the fancy method"],
        "close": "Two ears, one hop. Every adult once learned this too.",
    },
    {
        "slug": "getting-dressed", "emoji": "👕", "sort": 74,
        "title": "Getting Dressed Solo: Choices, Order, and Patience",
        "excerpt": "Backward shirts are a stage, not a failure. The order trick that fixes most struggles.",
        "intro": "Independent dressing = sequencing + motor skills + patience. Teach the ORDER explicitly — most struggles are sequence confusion, not laziness.",
        "sections": [
            ("Teach the order", [
                "Underwear → shirt → pants → socks → shoes. Say it as a chant.",
                "The tag trick: 'Tag in the back!' solves 80% of backward shirts",
                "Sit down for pants and shoes — standing dressing is advanced mode",
            ]),
            ("Remove the battles", [
                "Two outfits to choose from, picked by you the night before",
                "Weather-inappropriate choices: 'It is 40 degrees — which of THESE TWO keeps you warm?'",
                "Lay clothes in order, top to bottom — the pile IS the sequence",
            ]),
            ("Build the skills", [
                "Start with undressing — it is easier and builds confidence",
                "Big buttons before small, loose pants before tight",
                "Praise the attempt, fix the backwards shirt later (or not at all)",
            ]),
        ],
        "try": ["Teach the tag trick today", "Lay out clothes in order tonight", "Offer 2 choices tomorrow morning"],
        "close": "Backward today, independent tomorrow. It is all progress.",
    },
    {
        "slug": "hand-washing", "emoji": "🧼", "sort": 75,
        "title": "Hand Washing They'll Actually Do",
        "excerpt": "Twenty seconds is forever. The song, the glitter trick, and the step stool.",
        "intro": "Kids skip handwashing because it is boring and hard to reach. Fix the setup, add a song, and demonstrate WHY once — with glitter.",
        "sections": [
            ("The setup", [
                "Step stool at every sink — if they cannot reach comfortably, they will not do it",
                "Foam soap — one pump, fun texture, less waste",
                "Their own towel at their height",
            ]),
            ("The 20 seconds", [
                "Sing Happy Birthday twice — the classic timer",
                "Or the ABC song once — same length, more educational",
                "Scrub the 'spider webs' between fingers — imagery works",
            ]),
            ("The glitter germ lesson", [
                "Rub glitter on their hands: 'These are germs — try to rinse them off with just water.'",
                "They cannot. Then add soap — glitter surrenders.",
                "One demonstration beats 100 reminders.",
            ]),
            ("The routine anchors", [
                "Before eating, after bathroom, after coming inside — same 3, every day",
                "You wash with them the first month — modeling, not monitoring",
            ]),
        ],
        "try": ["Do the glitter demo this weekend", "Install the step stool", "Pick the family handwash song"],
        "close": "Show the germs once. The habit follows.",
    },
    {
        "slug": "naming-feelings", "emoji": "😊", "sort": 76,
        "title": "Name It to Tame It: Feelings Words for Ages 3–6",
        "excerpt": "Kids act out feelings they cannot name. Build the vocabulary, shrink the meltdowns.",
        "intro": "A child who can say 'I am frustrated' is a child who does not need to throw the block. Feelings vocabulary is emotional infrastructure.",
        "sections": [
            ("Teach the words in calm moments", [
                "Start with 6: happy, sad, angry, scared, frustrated, excited — with faces",
                "Our emotion flashcards make this a 2-minute daily game",
                "Name YOUR feelings out loud: 'I am frustrated this lid will not open.'",
            ]),
            ("Use them in the storm", [
                "Offer words, do not demand them: 'Are you angry? Or frustrated?'",
                "Accept pointing at a feelings chart — words come later",
                "After calming: 'You were SO angry. What helped?'",
            ]),
            ("Grow the vocabulary", [
                "Add: disappointed, nervous, proud, jealous, calm, silly — one a week",
                "Books are feelings teachers: 'How do you think HE feels?'",
                "The feelings journal printable gives them a daily check-in",
            ]),
        ],
        "try": ["Print the emotion flashcards", "Name your own feeling out loud 3x today", "Start the bedtime feelings check-in"],
        "close": "Feelings named are feelings manageable.",
    },
    {
        "slug": "taking-turns", "emoji": "🔄", "sort": 77,
        "title": "Taking Turns: Games That Teach Waiting",
        "excerpt": "Waiting is a muscle. Seven games that exercise it without a single lecture.",
        "intro": "Turn-taking is impulse control in disguise. Lectures do not build it — games with built-in waiting do.",
        "sections": [
            ("The games", [
                "Roll-and-move board games: waiting for your turn IS the lesson",
                "Catch: throw, wait, catch — the pause between is practice",
                "Card game War: flip, compare, wait — simple and perfect",
                "Building together: 'You add one, I add one' — collaborative waiting",
                "Cooking: stir, then WAIT for it to bake — delayed gratification, edible",
                "Red Light Green Light: freeze on command — impulse control as a sport",
                "Conversation ball: only the holder talks — physical turn-taking",
            ]),
            ("Support the skill", [
                "Use a visual timer for turns — 'when the sand runs out, my turn'",
                "Praise waiting specifically: 'You waited so patiently!'",
                "Start with SHORT waits and lengthen — like any muscle",
            ]),
        ],
        "try": ["Play War tonight", "Try red-light-green-light this weekend", "Use a timer for toy turns"],
        "close": "Every turn waited is impulse control earned.",
    },
    {
        "slug": "growing-empathy", "emoji": "💛", "sort": 78,
        "title": "Growing Empathy: 5 Daily Practices",
        "excerpt": "Empathy is not a trait — it is a habit. Five tiny practices that build it.",
        "intro": "Empathy grows the way muscles grow: with daily reps. Five practices, each under 2 minutes, that compound over years.",
        "sections": [
            ("The 5 practices", [
                "**Narrate feelings you see**: 'That boy fell — he might be scared. Should we check?'",
                "**The bedtime replay**: 'Who did you help today? Who helped you?'",
                "**Pet care**: feeding and gentle touch — responsibility plus tenderness",
                "**Thank-you notes**: draw one for grandparents monthly — gratitude in action",
                "**The feelings guess**: during books or shows — 'How is she feeling? How can you tell?'",
            ]),
            ("What NOT to do", [
                "Do not force apologies — forced sorry teaches performance, not empathy",
                "Do not shame: 'How would YOU feel?' as a weapon backfires",
                "Do model it: let them see you comfort, tip, thank, apologize",
            ]),
        ],
        "try": ["Narrate one stranger's feeling today", "Ask the bedtime help-question tonight", "Draw one thank-you note this week"],
        "close": "Empathy is caught, not taught. Be the model.",
    },
    {
        "slug": "losing-gracefully", "emoji": "🎲", "sort": 79,
        "title": "How to Lose a Board Game Without Melting Down",
        "excerpt": "The flip-the-board phase is normal. The coaching script that ends it.",
        "intro": "Hating to lose means they care — good. Your job is not to let them win; it is to teach the 30 seconds after losing.",
        "sections": [
            ("Before the game", [
                "Say it upfront: 'Someone will win and someone will lose. We play for fun.'",
                "Choose games with luck (Candy Land) over skill at first — losing to luck stings less",
                "Keep games SHORT — 10 minutes of losing beats 40",
            ]),
            ("The losing script", [
                "Model it constantly: 'Oh no, I lost! Good game — that was fun!'",
                "Teach the 3 steps: take a breath → say 'good game' → shake hands / high five",
                "Practice with stuffed animals: teddy loses gracefully, they coach him",
            ]),
            ("After a meltdown", [
                "Comfort first: losing hurts, acknowledge it — 'You really wanted to win.'",
                "Later, not during: 'What could we do next time we lose?'",
                "Never punish the meltdown — it is a skill gap, not defiance",
            ]),
        ],
        "try": ["Say the pre-game line before your next game", "Model a graceful loss this week", "Practice with stuffed animals"],
        "close": "Losing well is winning at character.",
    },
    {
        "slug": "making-friends", "emoji": "🤝", "sort": 80,
        "title": "Making Friends: Scripts for Shy Kids",
        "excerpt": "Shy kids do not need pushing — they need lines. The exact words that open play.",
        "intro": "Social skills are scripts before they are instincts. Give shy kids the actual words, rehearse at home, then let them try.",
        "sections": [
            ("The scripts", [
                "Joining play: 'Can I play too?' or 'What are you playing?'",
                "Starting: 'Hi, I am Sam. Want to build with me?'",
                "Sharing an idea: 'What if we make it a castle?'",
                "Leaving gracefully: 'I am going to play over there now. Bye!'",
            ]),
            ("Rehearse at home", [
                "Role-play with stuffed animals — they practice on teddy first",
                "Playground recon: arrive early when it is quiet, or bring a great toy (a ball invites joiners)",
                "One friend > crowd: arrange ONE playdate, not a party",
            ]),
            ("Support, do not rescue", [
                "Stay close but do not hover — nearby, not involved",
                "Debrief after: 'What was fun? What was hard?' — not 'Did you make friends?!'",
                "Some kids watch first — watching IS participating at this age",
            ]),
        ],
        "try": ["Rehearse 'can I play too' with teddy tonight", "Arrive at the playground 10 min early", "Schedule one 1-hour playdate"],
        "close": "Give them the words. The courage follows.",
    },
    {
        "slug": "apologizing-real", "emoji": "💌", "sort": 81,
        "title": "Apologizing for Real (Not Just 'Say Sorry')",
        "excerpt": "'Say sorry!' produces parrots. The 4-part apology that teaches repair.",
        "intro": "Forced apologies teach kids to say words without meaning. A real apology has 4 parts — teach the parts, and the meaning follows.",
        "sections": [
            ("The 4 parts", [
                "**What I did**: 'I knocked over your tower.' — name it specifically",
                "**How it affected them**: 'That made you sad — you worked hard on it.'",
                "**I am sorry**: the words, now with meaning behind them",
                "**How I will fix it**: 'Can I help rebuild it?' — repair is the point",
            ]),
            ("Teach it by modeling", [
                "Apologize to THEM when you mess up — 'I yelled, that scared you, I am sorry, I will take a breath next time.'",
                "This is the single most powerful apology lesson. Do it.",
            ]),
            ("When they are not ready", [
                "Do not force it in the moment — 'We will fix this when everyone is calm.'",
                "Help them repair first (rebuild the tower together), words later",
                "Some kids write/draw apologies easier than saying them",
            ]),
        ],
        "try": ["Apologize to your child for something real this week", "Teach the 4 parts at a calm moment", "Focus on repair over words next conflict"],
        "close": "Sorry is a verb before it is a word. Teach the doing.",
    },
    {
        "slug": "calm-down-corner", "emoji": "🛋️", "sort": 82,
        "title": "The Calm-Down Corner: Build It Right",
        "excerpt": "Not a punishment spot — a recharge station. What goes in, and how to introduce it.",
        "intro": "A calm-down corner works when kids CHOOSE it. That means building it together, stocking it well, and never, ever sending them there as punishment.",
        "sections": [
            ("What goes in", [
                "Soft seating: pillow, beanbag, or folded blanket",
                "Calming tools: a glitter jar (shake and watch settle), squishy ball, stuffed animal",
                "Feelings chart: point to the feeling — words optional",
                "Breathing visual: 'smell the flower, blow the candle' card",
                "2–3 quiet books — no exciting toys (it is calm-down, not playtime)",
            ]),
            ("How to introduce it", [
                "Build it TOGETHER on a calm day — 'This is your cozy spot for big feelings.'",
                "Practice using it when calm: visit, try the glitter jar, leave",
                "YOU use it too: 'I am feeling frustrated — I am going to the cozy spot.'",
            ]),
            ("The rules", [
                "Never send them there angry — invite: 'Want your cozy spot?'",
                "No time limits — they come out when calm",
                "After: reconnect, then problem-solve. The corner is step 1 of 3.",
            ]),
        ],
        "try": ["Build the corner together this weekend", "Make a glitter jar", "Practice visiting it while calm"],
        "close": "Everyone needs a place to regroup. Build theirs now.",
    },
    {
        "slug": "sharing-upgraded", "emoji": "🤲", "sort": 83,
        "title": "Sharing 2.0: Timers, Trades, and Turn-Taking",
        "excerpt": "Beyond 'be nice': the concrete systems that make sharing actually happen.",
        "intro": "Telling kids to share is abstract. Timers, trades, and turn systems are concrete — and concrete works at 3–6.",
        "sections": [
            ("The systems", [
                "**The timer turn**: 5 minutes each, timer decides — the timer is the boss, not you",
                "**The trade board**: 'I will trade you 10 minutes of the truck for the blocks' — negotiation practice",
                "**The waiting list**: write names on a whiteboard — visible fairness",
                "**Yours/mine/ours**: sort toys into 3 bins together — clarity prevents fights",
            ]),
            ("Playdates", [
                "Put away 2–3 special toys BEFORE friends arrive — no surprises",
                "Have a 'share basket' of communal toys ready",
                "Plan a collaborative activity (baking, building) — shared goals beat shared toys",
            ]),
            ("Praise the process", [
                "'You waited for your turn — that was hard and you did it.'",
                "Notice sharing you were not asked to notice — it multiplies",
            ]),
        ],
        "try": ["Sort toys into yours/mine/ours this weekend", "Try the timer turn once", "Prep the share basket before the next playdate"],
        "close": "Fair systems beat fair lectures.",
    },
]
