# Member articles, batch 1: Math (10) + Reading (10) + Science (8)
MEMBER_1 = [
    {
        "slug": "subtraction-roadmap", "emoji": "➖", "sort": 32,
        "title": "Subtraction Without Tears: The Take-Away Method",
        "excerpt": "Addition clicked but subtraction stalls? The concrete-to-abstract ladder that fixes it.",
        "intro": "Subtraction feels harder because 'taking away' is less intuitive than 'putting together.' The fix is not more worksheets — it is more time at the concrete stage.",
        "sections": [
            ("Stage 1: Real objects (1–2 weeks)", [
                "Start with snacks: 'You have 7 crackers. Eat 2. How many left?' Eating the answer is memorable.",
                "Use the words take away, give away, and left over — the vocabulary IS the concept",
                "Stay within 5 until it is effortless, then move to 10",
            ]),
            ("Stage 2: Draw it (1 week)", [
                "Draw 8 circles, cross out 3, count what is left — the crossing-out IS subtraction",
                "Let them draw the objects: silly drawings beat perfect circles",
                "Introduce the minus sign only after the action is solid",
            ]),
            ("Stage 3: Numbers only", [
                "Start with our Subtraction Practice pack — 5 problems a day",
                "Teach the 'count up' trick for 9 − 7: '7… 8, 9 — that is 2!'",
                "Never mix operations until each is fluent alone",
            ]),
        ],
        "try": ["Do 5 snack-subtractions at dinner this week", "Draw-and-cross-out 10 problems together", "Print the subtraction pack and try page 1"],
        "close": "Subtraction is just addition walking backwards. Walk it slowly.",
    },
    {
        "slug": "number-bonds-guide", "emoji": "🔗", "sort": 33,
        "title": "Number Bonds to 10: The Secret Behind Fast Mental Math",
        "excerpt": "Kids who 'just know' 8 + 5 know this first. The pairs that unlock everything.",
        "intro": "Number bonds are the pairs that make 10: 1+9, 2+8, 3+7, 4+6, 5+5. A child who owns these can break any bigger problem into easy steps.",
        "sections": [
            ("Why they matter", [
                "8 + 5 becomes 8 + 2 + 3 = 13 — impossible without knowing 8 needs 2",
                "They are the foundation of carrying, borrowing, and all mental math",
                "Schools test them constantly, often without teaching them directly",
            ]),
            ("How to teach them", [
                "**Ten-frame fill**: show 7 dots in a ten-frame — 'how many more to fill it?'",
                "**The handshake game**: you hold up 4 fingers, they hold up 6 — 'we make 10!'",
                "**Rainbow pairs**: write 1–9 in an arc, draw lines connecting pairs that make 10",
            ]),
            ("Make them stick", [
                "One pair a day, then cumulative review — 5 minutes max",
                "Quiz backwards: 'I have 3, how many more to make 10?'",
                "Celebrate instant answers; patiently re-teach slow ones",
            ]),
        ],
        "try": ["Play the handshake game at breakfast for a week", "Draw the rainbow pairs poster together", "Test: can they answer all pairs in under 30 seconds?"],
        "close": "Ten is the anchor of our number system. Bond with it.",
    },
    {
        "slug": "telling-time", "emoji": "🕐", "sort": 34,
        "title": "Telling Time: From O'Clock to Half Past",
        "excerpt": "Clocks are the hardest 'easy' skill. Teach the hands one at a time.",
        "intro": "Telling time combines numbers, fractions, and skip-counting — no wonder it is hard. The trick: teach one hand at a time, starting with a real clock they can touch.",
        "sections": [
            ("Step 1: The hour hand only", [
                "Cover the minute hand with tape — 'what number is the short hand pointing at?'",
                "Connect to their day: 'The short hand is on 8 — breakfast time!'",
                "Play 'set the clock': you say a time, they move the hand",
            ]),
            ("Step 2: O'clock and half past", [
                "O'clock: long hand on 12, short hand on the number — practice with real events",
                "Half past: 'halfway to the next number' — use a paper plate split in half to show it",
                "Our Telling Time printable has 12 practice clocks",
            ]),
            ("Step 3: Real life", [
                "Ask them the time before favorite events — motivation is the best teacher",
                "Get a cheap analog watch; digital clocks teach nothing about time",
                "Skip minutes-to-the-hour until o'clock and half-hour are instant",
            ]),
        ],
        "try": ["Tape the minute hand and practice hour-only for 3 days", "Print the telling-time pack", "Ask 'what time is it?' before dinner all week"],
        "close": "Time is abstract. Make it touchable first.",
    },
    {
        "slug": "money-basics", "emoji": "🪙", "sort": 35,
        "title": "Money Basics: Pennies, Nickels, and the Toy Store Game",
        "excerpt": "Coins teach skip-counting, decimals, and delayed gratification. Start with a store.",
        "intro": "Money is the most motivating math manipulative ever invented. A toy store at home teaches coin values faster than any worksheet.",
        "sections": [
            ("Learn the coins", [
                "One coin at a time: penny (1), nickel (5), dime (10), quarter (25) — size does NOT match value, say it out loud",
                "Sort a pile by coin type, then count each pile by skip-counting",
                "The rhyme: 'penny 1, nickel 5, dime 10, quarter 25 — now you know, give it a try!'",
            ]),
            ("The toy store game", [
                "Price 5–8 toys with simple tags: 7c, 12c, 25c…",
                "Give them a pile of real coins and a little wallet",
                "Start as the shopkeeper, then switch — being the shopkeeper teaches making change",
            ]),
            ("Level up", [
                "'You have 30c, the car costs 47c — how much more do you need?'",
                "Real store: let them hand the cashier coins and count change",
                "Introduce the piggy bank split: spend, save, share",
            ]),
        ],
        "try": ["Sort the coin jar together this weekend", "Set up the toy store with 5 priced toys", "Print the money-counting pack"],
        "close": "Money is math with a purpose. Kids can tell.",
    },
    {
        "slug": "measurement", "emoji": "📏", "sort": 36,
        "title": "Measurement for Little Hands: Longer, Heavier, Fuller",
        "excerpt": "Before rulers come comparisons. The sensory ladder to real measurement.",
        "intro": "Measurement starts with the body, not the ruler. Kids must feel 'longer' and 'heavier' dozens of times before numbers mean anything.",
        "sections": [
            ("Stage 1: Compare (no numbers)", [
                "Longer/shorter: line up shoes, pencils, arms — 'which is longer?'",
                "Heavier/lighter: hold one object in each hand, eyes closed",
                "Fuller/emptier: pour water between cups of different shapes — the classic surprise",
            ]),
            ("Stage 2: Non-standard units", [
                "'How many hands long is the table?' — measure everything in hands, feet, blocks",
                "Discover the problem: 'My 5 hands and your 5 hands are different!' — that is WHY we need rulers",
            ]),
            ("Stage 3: Real tools", [
                "Ruler: measure 5 favorite toys, line them up shortest to longest",
                "Kitchen scale: weigh fruit, guess first — estimation again",
                "Measuring cups while cooking: fractions you can eat",
            ]),
        ],
        "try": ["Measure 5 toys in 'hands' tonight", "Do the water-pouring fuller/emptier demo", "Weigh 3 fruits and order them"],
        "close": "Standard units were invented for a reason. Let them discover it.",
    },
    {
        "slug": "patterns-power", "emoji": "🔶", "sort": 37,
        "title": "Pattern Power: AB, ABB, and What's Next?",
        "excerpt": "Patterns are baby algebra. The progression from copying to creating.",
        "intro": "Every math topic — addition tables, multiplication, sequences — is pattern recognition. Pattern play at 3–6 is algebra prep in disguise.",
        "sections": [
            ("The progression", [
                "**Copy** (age 3): you build red-blue-red-blue, they copy it beside yours",
                "**Continue** (age 4): you start the pattern, they add the next 3",
                "**Name** (age 5): 'This is an AB pattern' — naming makes it portable",
                "**Create and challenge** (age 6): they invent ABB or ABC patterns for you to continue",
            ]),
            ("Pattern materials", [
                "Beads on a string, colored blocks, stickers in a row",
                "Body patterns: clap-stomp-clap-stomp — movement locks it in",
                "Nature patterns: leaf-rock-leaf-rock on a walk",
                "Sound patterns: tap-tap-BANG on the table",
            ]),
            ("Spot the error", [
                "Build a pattern with one wrong piece — 'can you find my mistake?'",
                "Kids LOVE catching parent mistakes. Use it.",
            ]),
        ],
        "try": ["Build 3 copy-me patterns with blocks today", "Try one body pattern at dinner", "Print the pattern-completion pack"],
        "close": "Math is the study of patterns. Start with beads.",
    },
    {
        "slug": "shapes-geometry", "emoji": "🔷", "sort": 38,
        "title": "Beyond Circle and Square: Geometry in Real Life",
        "excerpt": "Six shapes, real objects, and the 'shape hunt' that makes geometry stick.",
        "intro": "Kids learn shapes by touching and finding, not by flashcards. The goal: see geometry in the world, not just on paper.",
        "sections": [
            ("The core six", [
                "Circle, square, triangle, rectangle, oval, diamond — in that order of difficulty",
                "Teach with real objects first: a ball, a cracker, a sandwich half",
                "Count sides and corners together: 'The triangle has 3 sides — let's count!'",
            ]),
            ("The shape hunt", [
                "Pick one shape per week — find 10 in the house",
                "Photo safari: take pictures of shapes on a walk, make a collage",
                "Grocery store shapes: cans are cylinders, boxes are rectangles",
            ]),
            ("Build with shapes", [
                "Tangram-style: make a house from one square and one triangle",
                "Draw a robot using only shapes — then name each one",
                "Our shape-tracing pack builds the drawing muscles too",
            ]),
        ],
        "try": ["Do a 10-minute shape hunt for circles today", "Count sides on 3 household objects", "Print the shapes-and-colors pack"],
        "close": "The world is made of shapes. Point them out.",
    },
    {
        "slug": "estimation-games", "emoji": "🔮", "sort": 39,
        "title": "Estimation Games: The Skill Schools Forget",
        "excerpt": "Guessing well is a math superpower. Three jar games that build number sense.",
        "intro": "Estimation — making a smart guess — is tested on every standardized exam and taught almost nowhere. Three games fix that at home.",
        "sections": [
            ("The jar games", [
                "**Candy jar**: fill a jar, everyone guesses, count together. Closest wins. Repeat weekly — guesses get scary accurate.",
                "**Handful guess**: grab a handful of blocks, guess the count before counting. Teaches subitizing.",
                "**How many steps?**: guess the steps to the mailbox, then count. Distance estimation.",
            ]),
            ("Teach the strategy", [
                "Count a small part, then multiply: 'This corner has about 10 — there are 4 corners…'",
                "Compare to a known: 'More than 10? Less than 50?' — bracketing",
                "Always guess BEFORE counting. The guess is the exercise.",
            ]),
            ("Why it matters", [
                "Estimation catches silly mistakes: 'That answer cannot be right, it is way too big'",
                "It is the foundation of rounding, measuring, and mental math",
            ]),
        ],
        "try": ["Start a candy jar guessing game this week", "Play handful-guess at dinner", "Ask 'more than 10 or less than 10?' 5 times today"],
        "close": "A good guess beats a slow count. Teach both.",
    },
    {
        "slug": "word-problems", "emoji": "📝", "sort": 40,
        "title": "Word Problems: Turning Stories Into Math",
        "excerpt": "Kids who ace worksheets freeze on word problems. The translation method that unfreezes them.",
        "intro": "Word problems are not harder math — they are a translation task: story to numbers. Teach the translation explicitly.",
        "sections": [
            ("The 3-step translation", [
                "**Step 1 — Act it out**: use toys or snacks to play the story. '3 birds sat, 2 flew away' — move them.",
                "**Step 2 — Draw it**: circles for birds, cross out the ones that left",
                "**Step 3 — Write it**: only now write 3 − 2 = 1. The numbers come last.",
            ]),
            ("Key word detective", [
                "altogether / in all → add",
                "left / remain / take away → subtract",
                "each / share equally → divide (for older kids)",
                "Warn them: key words help but the STORY decides — always act it out first",
            ]),
            ("Make your own", [
                "Kids who write word problems understand them twice as well",
                "'Write a subtraction story about dinosaurs' — then solve each other's",
            ]),
        ],
        "try": ["Act out 3 word problems with snacks this week", "Have your child write one dinosaur word problem", "Draw-then-solve 5 problems together"],
        "close": "Math lives in stories. Teach them to translate.",
    },
    {
        "slug": "fractions-food", "emoji": "🍕", "sort": 41,
        "title": "Fractions With Food: Halves and Quarters You Can Eat",
        "excerpt": "Nobody understands fractions from a worksheet first. Start with pizza.",
        "intro": "Fractions are division you can see. Food makes them visible, touchable, and delicious — the perfect first manipulative.",
        "sections": [
            ("Halves first", [
                "Cut an apple in half: 'One apple, two halves — two pieces make the whole apple again.'",
                "Fold paper in half, then in half again — unfold and count the 4 parts: quarters!",
                "Share fairly: 'Split the sandwich so we both get the same.' Fairness is fraction motivation.",
            ]),
            ("The language", [
                "Say 'one half' and 'one quarter' — not 'a half piece'",
                "'Which is bigger, one half or one quarter?' — let them compare real pieces",
                "Half of 4 crackers, half of 6 grapes — fractions OF a group",
            ]),
            ("Kitchen fraction lab", [
                "Pizza night: count the slices, name the fraction each person gets",
                "Measuring cups: 'Fill it halfway' while cooking",
                "Orange segments: how many eighths in the orange?",
            ]),
        ],
        "try": ["Split one snack into halves together today", "Fold paper into quarters and count", "Name fractions at pizza night"],
        "close": "Fair shares are the original fractions.",
    },
    {
        "slug": "phonics-basics", "emoji": "🔡", "sort": 42,
        "title": "Phonics Basics: Letter Sounds in the Right Order",
        "excerpt": "Not A-B-C order. The sound sequence that gets kids blending fastest.",
        "intro": "Teaching letter sounds in alphabet order is slow. This sequence — s, a, t, p, i, n first — lets kids build real words after just 6 letters: sat, pat, tap, snap.",
        "sections": [
            ("The magic order", [
                "Group 1: s, a, t, p, i, n → words: sat, pin, tap, snap",
                "Group 2: m, d, g, o, c, k → words: dog, cat, mop, kid",
                "Group 3: e, u, r, h, b, f → words: bed, run, hug, fed",
                "Why: these letters combine into the most words the fastest — early wins matter",
            ]),
            ("How to teach each sound", [
                "One sound a day, 5 minutes: show it, say it, find it",
                "Stretchy sounds first (ssss, mmmm) — they are easier to blend",
                "Multi-sensory: trace it in sand while saying it",
            ]),
            ("From sounds to blending", [
                "After group 1: point at s-a-t slowly, then faster — 'sat!'",
                "If they struggle, YOU blend and they repeat — modeling is teaching",
                "Our word-families pack practices exactly this",
            ]),
        ],
        "try": ["Teach s-a-t-p this week, one a day", "Build 'sat' and 'pat' with letter cards", "Print the word-families pack"],
        "close": "Order matters. Six letters, real words, instant motivation.",
    },
    {
        "slug": "rhyming-games", "emoji": "🎵", "sort": 43,
        "title": "Rhyming Games: The #1 Predictor of Reading Success",
        "excerpt": "Hearing that cat and hat sound alike predicts reading better than knowing ABCs. Five games.",
        "intro": "Phonological awareness — hearing sounds in words — predicts reading success better than letter knowledge. Rhyming is its most fun doorway.",
        "sections": [
            ("The games", [
                "**Rhyme thief**: say a word, they steal it with a rhyme. 'Cat!' — 'Hat!' Keep the rally going.",
                "**Silly rhymes**: make up nonsense rhymes — 'zebra… klebra!' Nonsense counts.",
                "**Rhyme hunt**: find 3 things in the room that rhyme with 'wall' (ball, doll, hall)",
                "**Book echoes**: read rhyming books (Room on the Broom) and pause before the rhyme — they fill it in",
                "**Odd one out**: 'cat, hat, dog — which does not rhyme?'",
            ]),
            ("The progression", [
                "Hearing rhymes (age 3) → making rhymes (age 4) → rhyming on demand (age 5)",
                "Never correct a 'wrong' rhyme harshly — 'Hmm, does dog really sound like cat? Say them slowly…'",
            ]),
        ],
        "try": ["Play rhyme thief at dinner tonight", "Read one rhyming book with pause-and-fill", "Try odd-one-out with 5 sets"],
        "close": "Ears first, eyes later. Rhyming tunes the ears.",
    },
    {
        "slug": "read-aloud-pro", "emoji": "🎭", "sort": 44,
        "title": "Read-Aloud Like a Pro: Voices, Pauses, and Questions",
        "excerpt": "Fifteen minutes of reading aloud beats any app. How to make those minutes magic.",
        "intro": "Reading aloud is the single highest-ROI learning activity for ages 3–6. But HOW you read matters as much as THAT you read.",
        "sections": [
            ("The techniques", [
                "**Voices**: a different voice per character — silly voices are remembered",
                "**Pauses**: stop before exciting moments — 'And then… (pause) …the door opened!'",
                "**Point as you read**: their eyes follow your finger and learn print direction",
                "**Predict**: 'What do you think happens next?' — then keep reading to check",
            ]),
            ("The questions (after, not during)", [
                "'Who was your favorite character and why?'",
                "'What would YOU do if you were the bear?'",
                "'Did that remind you of anything?' — connecting book to life",
            ]),
            ("Build the habit", [
                "Same time daily — bedtime is classic for a reason",
                "Let them choose, even the same book 50 times — repetition is learning",
                "Keep books everywhere: bathroom, car, kitchen — access beats intention",
            ]),
        ],
        "try": ["Add one voice to tonight's book", "Ask one 'what would you do' question", "Put a book basket in the bathroom"],
        "close": "You are not reading a book. You are building a reader.",
    },
    {
        "slug": "book-list-3-4", "emoji": "📚", "sort": 45,
        "title": "25 Books Every 3–4 Year Old Loves",
        "excerpt": "Tested, re-read, and begged-for-again: the picture books that never miss.",
        "intro": "The right book at 3 is short, rhythmic, and slightly silly. This list is organized by what kids actually ask for again.",
        "sections": [
            ("Rhythm and rhyme", [
                "Room on the Broom — Julia Donaldson (the rhyming gold standard)",
                "Giraffes Can't Dance — Giles Andreae (rhythm + message)",
                "Each Peach Pear Plum — Janet & Allan Ahlberg (I-spy rhymes)",
                "Brown Bear, Brown Bear — Bill Martin Jr. (pattern + prediction)",
                "The Gruffalo — Julia Donaldson (repetition kids memorize)",
            ]),
            ("Silly and interactive", [
                "Press Here — Hervé Tullet (the book is a game)",
                "Don't Let the Pigeon Drive the Bus — Mo Willems (kids LOVE yelling NO)",
                "Where the Wild Things Are — Maurice Sendak (imagination + return home)",
                "The Pigeon Needs a Bath — Mo Willems (bath-time tie-in)",
                "Dragons Love Tacos — Adam Rubin (absurdity wins)",
            ]),
            ("Feelings and everyday life", [
                "The Feelings Book — Todd Parr (simple, bright, perfect)",
                "Llama Llama Misses Mama — Anna Dewdney (first-day-of-school feelings)",
                "Corduroy — Don Freeman (gentle classic)",
                "Knuffle Bunny — Mo Willems (lost toy panic, resolved)",
                "Owl Babies — Martin Waddell (separation anxiety, soothed)",
            ]),
            ("Bedtime winners", [
                "Goodnight Moon — Margaret Wise Brown (the ritual book)",
                "Time for Bed — Mem Fox (every animal sleeps)",
                "The Going to Bed Book — Sandra Boynton (silly + short)",
                "Guess How Much I Love You — Sam McBratney (the love-measuring classic)",
                "Good Night, Gorilla — Peggy Rathmann (nearly wordless, hilarious)",
            ]),
            ("First favorites to grow with", [
                "The Very Hungry Caterpillar — Eric Carle (days, food, metamorphosis)",
                "Where's Spot? — Eric Hill (lift-the-flap perfection)",
                "Dear Zoo — Rod Campbell (flaps + animals)",
                "The Snowy Day — Ezra Jack Keats (a classic for a reason)",
                "Freight Train — Donald Crews (colors + motion words)",
            ]),
        ],
        "try": ["Pick 3 from this list at your next library trip", "Try one rhyming book with pause-and-fill", "Start a fridge list of books they request again"],
        "close": "The best book is the one they ask for again.",
    },
    {
        "slug": "book-list-5-6", "emoji": "📖", "sort": 46,
        "title": "25 Books That Turn 5–6 Year Olds Into Readers",
        "excerpt": "Longer stories, first chapters, and books they can start reading themselves.",
        "intro": "At 5–6, kids are ready for real plots and early readers they can tackle solo. Mix read-alouds (richer) with I-can-read books (confidence).",
        "sections": [
            ("Read-aloud adventures", [
                "The Wild Robot — Peter Brown (robot + nature, gorgeous)",
                "My Father's Dragon — Ruth Stiles Gannett (first chapter book for many)",
                "The Tale of Despereaux — Kate DiCamillo (brave mouse, big heart)",
                "Charlotte's Web — E.B. White (the cry-with-your-kid classic)",
                "James and the Giant Peach — Roald Dahl (pure imagination)",
            ]),
            ("Early readers they can read", [
                "Elephant & Piggie series — Mo Willems (dialogue format = easy + funny)",
                "Dog Man — Dav Pilkey (graphic novel gateway)",
                "Fly Guy — Tedd Arnold (silly, simple, boy-approved)",
                "Pete the Cat: I Love My White Shoes — James Dean (repetition + song)",
                "Biscuit series — Alyssa Satin Capucilli (gentle first reader)",
            ]),
            ("Nonfiction they will devour", [
                "National Geographic Little Kids First Big Books (animals, ocean, dinosaurs)",
                "The Boy Who Loved Math — Deborah Heiligman (biography as story)",
                "Actual Size — Steve Jenkins (animals at real scale — mind-blowing)",
                "Diary of a Worm — Doreen Cronin (funny + science)",
                "What Do You Do With an Idea? — Kobi Yamada (creativity celebration)",
            ]),
            ("Classics that still work", [
                "Where the Sidewalk Ends — Shel Silverstein (poems they will memorize)",
                "The Giving Tree — Shel Silverstein (discuss it together)",
                "Frog and Toad Are Friends — Arnold Lobel (gentle friendship)",
                "Amelia Bedelia — Peggy Parish (literal-minded hilarity)",
                "Curious George — H.A. Rey (curiosity with consequences)",
            ]),
            ("Series that hook them", [
                "Magic Tree House — Mary Pope Osborne (history + adventure, 30+ books)",
                "The Bad Guys — Aaron Blabey (funny villains trying to be heroes)",
                "Owl Diaries — Rebecca Elliott (diary format, girl-approved)",
                "Narwhal and Jelly — Ben Clanton (graphic novel sweetness)",
                "Puppy Place — Ellen Miles (one puppy per book — collect them all)",
            ]),
        ],
        "try": ["Start one read-aloud chapter book this week", "Let them pick 2 early readers at the library", "Try one nonfiction — watch what happens"],
        "close": "Series are magic: finishing one creates hunger for the next.",
    },
    {
        "slug": "comprehension-questions", "emoji": "💬", "sort": 47,
        "title": "Reading Comprehension: 5 Questions After Every Book",
        "excerpt": "Reading the words is half the job. Five questions that build the other half.",
        "intro": "Comprehension — understanding and thinking about the story — is what turns decoding into reading. Five questions, asked casually after any book.",
        "sections": [
            ("The five questions", [
                "**Retell**: 'Can you tell me what happened, in order?' — sequencing",
                "**Favorite**: 'What was your favorite part? Why?' — opinion + evidence",
                "**Feelings**: 'How do you think she felt when…?' — empathy + inference",
                "**Predict**: 'What do you think happens next?' — or before reading: '…from the cover?'",
                "**Connect**: 'Did that remind you of anything in YOUR life?' — the deepest one",
            ]),
            ("How to ask without quizzing", [
                "Ask during snacks or walks, not with the book open like a test",
                "Answer the questions yourself first — model thinking out loud",
                "Accept any answer, then wonder together: 'Hmm, interesting — I thought…'",
            ]),
        ],
        "try": ["Ask just the 'connect' question after tonight's book", "Model a retell of YOUR day first", "Try 'what happens next' before opening a new book"],
        "close": "Comprehension is conversation. Just talk about the book.",
    },
    {
        "slug": "reluctant-readers", "emoji": "🚪", "sort": 48,
        "title": "For the Kid Who 'Hates' Reading: 7 Back Doors In",
        "excerpt": "Nobody hates stories. They hate struggling. Seven ways around the resistance.",
        "intro": "Reluctant readers are usually kids who found reading hard and decided to hate it before it could embarrass them. Never fight the label — sneak around it.",
        "sections": [
            ("The back doors", [
                "**Comics and graphic novels**: Dog Man counts as reading. Full stop.",
                "**Joke books**: reading 50 jokes to the family is 50 sentences of practice",
                "**Nonfiction obsession**: dinosaurs, space, sharks — follow the obsession, the reading follows",
                "**Audiobooks + print**: listen in the car, then 'read along' with the book at home",
                "**Cooking**: recipes must be read to be followed — delicious motivation",
                "**Game instructions**: new board game? They read the rules.",
                "**Notes and mail**: leave silly notes on their pillow; get excited about real mail",
            ]),
            ("What NOT to do", [
                "Do not assign reading as punishment or homework-like duty",
                "Do not correct every mistake — fluency dies under constant correction",
                "Do not compare to siblings or friends. Ever.",
            ]),
        ],
        "try": ["Get one joke book from the library this week", "Leave a silly note on their pillow tonight", "Try an audiobook on the next car ride"],
        "close": "They do not hate reading. They hate feeling bad at it. Remove the bad feeling.",
    },
    {
        "slug": "reading-nook", "emoji": "🛋️", "sort": 49,
        "title": "Build a Reading Nook for Under $30",
        "excerpt": "A special spot makes reading feel like a treat. The 5 ingredients of a nook kids use.",
        "intro": "Kids read more when reading has a PLACE. A nook does not need to be fancy — it needs to be theirs.",
        "sections": [
            ("The 5 ingredients", [
                "**Defined space**: a corner, a closet with the door off, under a table with a sheet — boundaries make it special",
                "**Soft seating**: pillows, a beanbag, or a folded comforter — $10–15",
                "**Good light**: a clip lamp or string lights — $5–8",
                "**Book access**: a small shelf or basket with 8–12 books, rotated monthly",
                "**One personal touch**: their name on the wall, a stuffed reading buddy",
            ]),
            ("Make it work", [
                "Let them help build it — ownership drives use",
                "No screens in the nook. Ever. It is sacred.",
                "Rotate books monthly; a 'new' old book feels fresh",
                "Siblings can share, but each needs a personal corner item",
            ]),
        ],
        "try": ["Pick the corner together this weekend", "Move 10 books into a basket there", "Add one string of lights"],
        "close": "Place shapes behavior. Give reading a home.",
    },
    {
        "slug": "storytelling-skills", "emoji": "🎤", "sort": 50,
        "title": "Storytelling Skills: From Rambling to Real Narratives",
        "excerpt": "'And then… and then… and then…' — how to teach beginning, middle, and end.",
        "intro": "Telling a coherent story is a top kindergarten-readiness skill. Most kids ramble because nobody taught them story structure. Three tools fix it.",
        "sections": [
            ("Tool 1: Story stones", [
                "Draw simple pictures on 6 stones: a character, a place, an object, a problem, a helper, an ending",
                "They draw 3 stones and must use all three — constraints create stories",
            ]),
            ("Tool 2: First-next-last", [
                "After any event: 'What happened FIRST? What happened NEXT? What happened LAST?'",
                "Do it about their day before you do it about books — their life is the easiest material",
            ]),
            ("Tool 3: The story hand", [
                "Hold up a hand: thumb = characters, pointer = setting, middle = problem, ring = events, pinky = ending",
                "Trace the hand while they tell — a physical map for the story",
            ]),
            ("Level up", [
                "Record them telling a story and play it back — kids LOVE this and self-correct",
                "Our story-sequencing printable gives them panels to draw in order",
            ]),
        ],
        "try": ["Do first-next-last about today at dinner", "Make 6 story stones this weekend", "Record one story and play it back"],
        "close": "Every ramble is a story trying to get organized. Hand them the map.",
    },
    {
        "slug": "audiobooks-right", "emoji": "🎧", "sort": 51,
        "title": "Audiobooks Count Too: How to Use Them Right",
        "excerpt": "Listening builds vocabulary and story sense. The right way to add audiobooks to the mix.",
        "intro": "Audiobooks build vocabulary, syntax, and story structure — everything except decoding. For ages 3–6, they are a supplement, not a substitute, for print.",
        "sections": [
            ("When they shine", [
                "Car rides: a 20-minute drive is a chapter — no screens needed",
                "Quiet time: audiobook + coloring beats tablet every time",
                "Bedtime: a sleep timer ends the story without you having to be there",
            ]),
            ("The read-along upgrade", [
                "Get the print book too — following along connects sounds to print",
                "Pause and predict, just like with read-alouds",
                "After finishing: 'Should we get the next one?' — series hook them",
            ]),
            ("Good starters", [
                "Winnie-the-Pooh (gentle, funny, perfect narration)",
                "The Gruffalo (short — try before committing)",
                "Magic Tree House (adventure series, 1 hour each)",
                "Your library app (Libby) has thousands free — start there",
            ]),
        ],
        "try": ["Install Libby and borrow one audiobook", "Try it on the next 20-minute drive", "Pair it with the print book once"],
        "close": "Ears can read too. Feed them stories.",
    },
    {
        "slug": "sink-or-float", "emoji": "💧", "sort": 52,
        "title": "Sink or Float: The Classic Experiment, Upgraded",
        "excerpt": "The simplest science experiment ever — plus the 3 twists that make it a real investigation.",
        "intro": "Sink-or-float is classic because it teaches the scientific method in 10 minutes: predict, test, observe, conclude. Three twists make it fresh.",
        "sections": [
            ("The basic setup", [
                "A tub of water, 8–10 objects: cork, coin, sponge, apple, spoon, leaf, toy car, ice cube",
                "Make a chart: two columns, SINK and FLOAT — they place each object after testing",
                "ALWAYS guess first. The guess is the science.",
            ]),
            ("Twist 1: The sponge surprise", [
                "A dry sponge floats. Push it underwater — it sinks! Why? (It filled with water — air vs. water weight)",
                "Kids remember surprises. Engineer one.",
            ]),
            ("Twist 2: Change one thing", [
                "Crumple foil into a tight ball (sinks) vs. shape it into a boat (floats) — same material, different shape!",
                "This is the seed of real experimental thinking: change ONE variable",
            ]),
            ("Twist 3: The orange test", [
                "An unpeeled orange floats; a peeled one sinks. Let them figure out why.",
                "(Answer: the peel is full of tiny air pockets — like a life jacket)",
            ]),
        ],
        "try": ["Run the basic version at bath time tonight", "Try the foil boat twist this weekend", "Use our science journal printable to record results"],
        "close": "Predict, test, gasp. That is the whole scientific method.",
    },
    {
        "slug": "growing-beans", "emoji": "🌱", "sort": 53,
        "title": "Growing Beans in a Cup: A 2-Week Science Project",
        "excerpt": "A damp paper towel, a bean, and a window — the most reliable wow in kid science.",
        "intro": "This is the highest-success-rate science project for ages 3–6: nearly free, nearly foolproof, and genuinely thrilling when the sprout appears.",
        "sections": [
            ("Setup (5 minutes)", [
                "Clear cup, damp (not soaked) paper towel, 2–3 dried beans pressed against the glass",
                "Plastic wrap over the top with a few holes — mini greenhouse",
                "Windowsill, not direct blazing sun",
            ]),
            ("The 2-week observation", [
                "Day 2–3: the bean swells — draw it in our planting log",
                "Day 4–5: a root appears, growing DOWN (ask: why down?)",
                "Day 7–10: the sprout pushes UP, then leaves unfold",
                "Measure daily with a ruler — measurement + science in one",
            ]),
            ("The questions to ask", [
                "'What does the plant need?' — let them discover water + light by testing",
                "Grow 2 cups: one in light, one in a dark box — compare",
                "'Where will the root go?' before it appears — prediction practice",
            ]),
        ],
        "try": ["Set up the cup together today", "Print the planting log", "Start a second cup in the dark as an experiment"],
        "close": "Two weeks of watching beats two hours of being told.",
    },
    {
        "slug": "weather-watch", "emoji": "🌤️", "sort": 54,
        "title": "Weather Watchers: Clouds, Rain Gauges, and Wind",
        "excerpt": "Meteorology for preschoolers: a rain gauge from a bottle and cloud-spotting walks.",
        "intro": "Weather is the perfect science topic: it changes daily, it is free, and kids can measure it themselves.",
        "sections": [
            ("Build a rain gauge", [
                "Cut the top off a plastic bottle, flip it as a funnel, tape a ruler to the side",
                "After each rain: read, record in our weather tracker, empty",
                "'How much rain did we get?' — real data, real pride",
            ]),
            ("Cloud spotting", [
                "Three types are enough: puffy (cumulus), flat gray (stratus), wispy (cirrus)",
                "'What do the clouds look like today? What does that mean for our plans?'",
                "Lie on a blanket and find shapes — science + imagination",
            ]),
            ("Wind and temperature", [
                "Ribbon on a stick = wind detector. Which way does it blow?",
                "A simple outdoor thermometer — read it together each morning",
                "The question that builds thinking: 'Yesterday was sunny and today is cloudy — what changed?'",
            ]),
        ],
        "try": ["Build the rain gauge this weekend", "Learn the 3 cloud types on your next walk", "Print the 7-day weather tracker"],
        "close": "The sky is a laboratory that restocks itself daily.",
    },
    {
        "slug": "magnet-magic", "emoji": "🧲", "sort": 55,
        "title": "Magnet Magic: 5 Experiments for the Fridge Door",
        "excerpt": "Invisible force, visible wow. Five magnet experiments with stuff from the junk drawer.",
        "intro": "Magnets feel like magic because the force is invisible. Five experiments turn the mystery into understanding — no special kit needed.",
        "sections": [
            ("The experiments", [
                "**Treasure sort**: a magnet + a pile of objects — sort into STICKS and DOESN'T STICK. (Surprise: not all metal sticks!)",
                "**Through the table**: move a paperclip under a thin table with a magnet on top — force through solid matter",
                "**Floating paperclip**: tie a paperclip to a string, hold the magnet above — it floats mid-air",
                "**Magnet maze**: draw a maze on cardboard, guide a paperclip 'car' with a magnet underneath",
                "**How strong?**: how many paperclips can your magnet hold in a chain? Test every magnet in the house.",
            ]),
            ("The big idea to land", [
                "Magnets pull SOME metals (iron, steel) — not all metal. Let them discover this; do not announce it.",
                "'What do you think will happen?' before every test — prediction is the habit",
            ]),
        ],
        "try": ["Do the treasure sort tonight", "Try the floating paperclip this weekend", "Rank all your fridge magnets by chain length"],
        "close": "Invisible forces are real. Let them feel one.",
    },
    {
        "slug": "color-mixing-lab", "emoji": "🎨", "sort": 56,
        "title": "Color Mixing Lab: What Happens When…?",
        "excerpt": "Food coloring, water, and ice cube trays — the chemistry lab every kitchen already has.",
        "intro": "Color mixing is chemistry for little hands: hypothesis ('what will red + blue make?'), experiment, observe. All with dish-safe materials.",
        "sections": [
            ("The lab setup", [
                "Ice cube tray + water + food coloring: 3 primary colors in 3 wells",
                "An eyedropper or spoon for transferring — fine motor bonus",
                "White paper underneath to see true colors",
            ]),
            ("The experiments", [
                "Red + yellow = ? Blue + yellow = ? Red + blue = ? — guess first, always",
                "'Can you make orange DARKER? LIGHTER?' — add more color, add more water",
                "Walking water: 3 cups, paper towel bridges, watch color travel — capillary action!",
                "Milk fireworks: milk + drops of color + touch of dish soap — swirls on their own",
            ]),
            ("Record like a scientist", [
                "Draw the 'before' colors and 'after' colors in our science journal",
                "'What surprised you?' — the most important lab question",
            ]),
        ],
        "try": ["Mix the 3 secondary colors tonight", "Try walking water this weekend", "Record results in the science journal"],
        "close": "Chemistry is just cooking with more questions.",
    },
    {
        "slug": "shadow-play", "emoji": "🌑", "sort": 57,
        "title": "Shadow Play: Light, Shapes, and Sundials",
        "excerpt": "A flashlight and a dark room teach more optics than any video. Plus a real sundial.",
        "intro": "Shadows teach that light travels straight and objects block it — big ideas, zero cost. All you need is a flashlight and curiosity.",
        "sections": [
            ("Indoor shadow lab", [
                "Flashlight + toys on the wall: move the toy closer/farther — 'why did the shadow get bigger?'",
                "Hand shadows: the classic dog, bird, rabbit — then invent your own",
                "Colored cellophane over the flashlight: do shadows have color?",
            ]),
            ("Outdoor shadow science", [
                "Trace your shadow with chalk at 9 AM, noon, and 4 PM — same person, three sizes",
                "'Why is the noon shadow tiny?' — the sun's position, discovered not told",
                "Shadow tag: step on each other's shadows instead of bodies",
            ]),
            ("Build a sundial", [
                "Stick a pencil through a paper plate, mark the shadow each hour with the time",
                "Next day: 'What time is it?' — read from THEIR sundial",
            ]),
        ],
        "try": ["Do hand shadows tonight", "Trace shadows at 2 different times tomorrow", "Build the paper-plate sundial this weekend"],
        "close": "Light is invisible until something blocks it. Block things.",
    },
    {
        "slug": "ice-melt-race", "emoji": "🧊", "sort": 58,
        "title": "The Great Ice Melt Race",
        "excerpt": "Three ice cubes, three conditions, one winner. A race that teaches variables.",
        "intro": "What melts ice fastest — salt, sun, or warm water? This race teaches fair testing: change one thing at a time.",
        "sections": [
            ("The race setup", [
                "3 identical ice cubes in 3 bowls: one plain, one with salt sprinkled on, one in warm water",
                "Everyone predicts the winner BEFORE starting — write predictions down",
                "Check every 5 minutes. The salt one surprises most kids.",
            ]),
            ("Make it a real experiment", [
                "Change ONE thing: same ice, same bowls, only the condition differs",
                "'Why do you think the salty one melted faster?' — let them theorize wildly",
                "Repeat with sugar vs. salt — is it the salt, or anything grainy?",
            ]),
            ("Extensions", [
                "Freeze small toys in a big ice block — 'rescue' them with salt and warm water droppers",
                "Ice cube painting: freeze watercolors in a tray, paint as they melt",
            ]),
        ],
        "try": ["Run the 3-bowl race this weekend", "Write predictions first — non-negotiable", "Try the toy rescue version next time"],
        "close": "The best experiments end with 'let's do it again but…'",
    },
    {
        "slug": "senses-walk", "emoji": "👃", "sort": 59,
        "title": "The 5-Senses Walk: Science With No Equipment",
        "excerpt": "See, hear, smell, touch, taste — a walk structured around the five senses.",
        "intro": "Scientists observe. This walk trains observation through all five senses — no equipment, just attention and a simple structure.",
        "sections": [
            ("The structure", [
                "Walk in 5 short legs, one sense each: 'For the next 2 minutes, we only use our EARS.'",
                "Ears: close eyes for 30 seconds — list every sound",
                "Eyes: find 5 shades of green / 3 circles / something tiny",
                "Nose: smell bark, flowers, rain on pavement — 'what does it remind you of?'",
                "Touch: rough/smooth/squishy hunt — collect in a bag",
                "Taste: bring 2 snacks — 'describe it without saying yummy'",
            ]),
            ("Record it", [
                "Draw one thing per sense in our science journal when you get home",
                "'Which sense told you the most today?'",
            ]),
        ],
        "try": ["Do the ears-only 2 minutes on your next walk", "Try the touch hunt with a bag", "Draw the 5-senses page after"],
        "close": "Attention is a muscle. Walks are the gym.",
    },
]
