# Member articles, batch 3: Learning Skills (8) + Health & Routines (5)
MEMBER_3 = [
    {
        "slug": "puzzles-by-age", "emoji": "🧩", "sort": 84,
        "title": "Puzzles by Age: Which Ones and Why",
        "excerpt": "Too easy bores, too hard frustrates. The piece-count guide plus the struggle sweet spot.",
        "intro": "Puzzles build spatial reasoning, patience, and the willingness to struggle — the exact traits school rewards. Match the difficulty right and they do the rest.",
        "sections": [
            ("Piece counts by age", [
                "Age 3: 4–12 pieces, big knobs or chunky pieces — completion in 5 minutes",
                "Age 4: 12–24 pieces — introduce edge-first strategy by modeling",
                "Age 5: 24–48 pieces — they can sort by color now",
                "Age 6: 48–100 pieces — multi-session puzzles teach persistence",
            ]),
            ("Teach the strategies", [
                "Edges first — say it every time until they say it",
                "Sort by color or picture area before assembling",
                "Flip all pieces face-up — the 'puzzle prep' ritual",
            ]),
            ("The struggle sweet spot", [
                "Help just enough that they finish in 15–20 minutes — then STOP helping",
                "If they quit, the puzzle was too hard. Go down a level, no shame.",
                "Do puzzles TOGETHER sometimes — your calm struggling is the lesson",
            ]),
        ],
        "try": ["Check: is their current puzzle in the sweet spot?", "Model edge-first once this week", "Try a 48-piece puzzle together"],
        "close": "Every piece placed is a small victory. Collect them.",
    },
    {
        "slug": "memory-games", "emoji": "🧠", "sort": 85,
        "title": "Memory Games: 7 Ways to Train Recall",
        "excerpt": "Memory is trainable. Seven games from tray games to story chains.",
        "intro": "Working memory — holding information while using it — underpins reading and math. It is also highly trainable through play.",
        "sections": [
            ("The 7 games", [
                "**Tray game**: 6 objects on a tray, 30 seconds to look, cover, 'what was there?'",
                "**Concentration**: face-down pairs, flip two — start with 6 pairs",
                "**I went to the store**: 'I bought apples…' each player adds one, reciting the whole list",
                "**Story chain**: build a story one sentence at a time, retelling from the start",
                "**Copy the sequence**: clap-stomp-snap patterns of growing length",
                "**Missing object**: line up toys, they close eyes, you remove one — which is missing?",
                "**Song lyrics**: learn verses by heart — music is memory glue",
            ]),
            ("Make it work", [
                "Start easy enough to WIN — confidence fuels effort",
                "Increase by ONE item when they master a level",
                "Play in short bursts — tired brains do not consolidate",
            ]),
        ],
        "try": ["Play the tray game tonight with 6 objects", "Start a story chain at dinner", "Try concentration with 6 pairs"],
        "close": "Memory is a muscle. Play is the gym.",
    },
    {
        "slug": "listening-games", "emoji": "👂", "sort": 86,
        "title": "Listening Games: Simon Says and Beyond",
        "excerpt": "'They never listen!' — maybe they never practiced. Six games that train ears.",
        "intro": "Listening is a skill, not a character trait. Kids who 'do not listen' usually never practiced focused listening as a game.",
        "sections": [
            ("The 6 games", [
                "**Simon Says**: the classic — add silly actions, and let THEM be Simon",
                "**Sound detective**: eyes closed — 'how many sounds can you hear? What are they?'",
                "**Whisper chain**: pass a whispered message around — giggles guaranteed",
                "**Clap the syllables**: 'el-e-phant' — 3 claps. Listening meets phonics.",
                "**Musical statues with tasks**: freeze, then 'touch something blue' — listen THEN move",
                "**Story listening**: read a page, close the book — 'what did the bear do?'",
            ]),
            ("Build the habit", [
                "Get eye contact BEFORE giving instructions — 'eyes on me first'",
                "One instruction at a time for under-5s — their buffer is small",
                "Have them repeat it back: 'Tell me what we are doing first.'",
            ]),
        ],
        "try": ["Play sound detective on your next walk", "Let them be Simon tonight", "Use 'eyes on me first' for one week"],
        "close": "Ears are trained, not born. Train them playfully.",
    },
    {
        "slug": "sorting-classifying", "emoji": "🗂️", "sort": 87,
        "title": "Sorting & Classifying: The Pre-Math Skill",
        "excerpt": "Before numbers come categories. The sorting progression from colors to Venn diagrams.",
        "intro": "Sorting — noticing what is same and different — is the cognitive foundation of all math: sets, categories, attributes. And it starts with laundry.",
        "sections": [
            ("The progression", [
                "Sort by ONE obvious trait: color (age 3) — buttons, blocks, socks",
                "Sort by shape or size (age 4) — 'big red ones here, small red ones there'",
                "Sort by TWO traits (age 5): red AND round vs. red AND square — this is hard, celebrate it",
                "Sort by rule THEY invent (age 6): 'Sort these however you want — then tell me your rule'",
            ]),
            ("Everyday sorting", [
                "Laundry: lights/darks, then socks by owner",
                "Groceries: fridge things vs. pantry things while unpacking",
                "Toy cleanup: the fastest daily sorting practice there is",
                "Nature: sort collected leaves by size, color, edge shape",
            ]),
            ("The thinking questions", [
                "'What is your sorting rule?' — articulating the rule is the math",
                "'Is there another way to sort these?' — flexibility of thought",
                "'Which group has more? How do you know?' — sorting meets counting",
            ]),
        ],
        "try": ["Sort laundry by color together once", "Ask 'what is your rule' during toy cleanup", "Try a two-trait sort with buttons"],
        "close": "Categories are the invisible skeleton of math. Build it early.",
    },
    {
        "slug": "observation-games", "emoji": "🔍", "sort": 88,
        "title": "Observation Games: I Spy, Upgraded",
        "excerpt": "Noticing details is a superpower. Five games that sharpen young eyes.",
        "intro": "Observation — really SEEING — underlies science, reading (letter shapes!), and safety. Five games that train it.",
        "sections": [
            ("The 5 games", [
                "**I Spy, leveled up**: 'I spy something with 4 legs AND brown' — two clues, real deduction",
                "**Spot the difference**: two nearly-identical toy setups — 'what did I change?'",
                "**Detail drawing**: draw a leaf while LOOKING at it — 'what do you notice?'",
                "**Photo zoom**: take close-up photos of household objects — guess what they are",
                "**The detective walk**: 'Find 3 things that were not here yesterday.'",
            ]),
            ("Build the habit", [
                "Model noticing: 'Look at the veins on this leaf!' — wonder is contagious",
                "Slow down: observation cannot be rushed. One object, 2 minutes.",
                "Our scavenger hunt printable structures a whole observation walk",
            ]),
        ],
        "try": ["Play two-clue I Spy today", "Change 3 things in their room — can they spot them?", "Draw one leaf from life"],
        "close": "The world is full of details. Teach them to collect some.",
    },
    {
        "slug": "building-challenges", "emoji": "🏗️", "sort": 89,
        "title": "10 Building Challenges for Blocks and LEGO",
        "excerpt": "Free building is great. Challenges are better. Ten prompts that stretch young engineers.",
        "intro": "Open-ended building builds creativity; CHALLENGES build engineering thinking: constraints, planning, testing. Alternate both.",
        "sections": [
            ("The 10 challenges", [
                "Build the tallest tower that stands for 10 seconds",
                "Build a bridge a toy car can drive under",
                "Build an animal using only 10 pieces",
                "Build a house for a stuffed animal — with a door it fits through",
                "Copy this photo/building (print or show a picture)",
                "Build something that can hold this book",
                "Build a maze a marble can roll through",
                "Build your name in 3D",
                "Build the same thing twice — exactly the same",
                "Build something that moves (wheels, hinges, ramps)",
            ]),
            ("Coach the engineering", [
                "Ask before helping: 'What is your plan?' — planning is the skill",
                "When it collapses: 'What fell first? What could hold it?' — failure analysis, kindly",
                "Photograph builds — a gallery wall honors the work",
            ]),
        ],
        "try": ["Try the bridge challenge this weekend", "Ask 'what is your plan' before the next build", "Start a build photo gallery"],
        "close": "Engineers are just kids whose collapses were celebrated.",
    },
    {
        "slug": "quiet-time", "emoji": "🤫", "sort": 90,
        "title": "Quiet Time: The Sanity-Saving Habit for Ages 3–6",
        "excerpt": "They outgrew naps but not the need for rest. How to build 45 minutes of quiet.",
        "intro": "When naps end (usually 3–4), afternoons fall apart. Quiet time — independent calm play — saves the day for everyone. But it must be TAUGHT.",
        "sections": [
            ("Set it up", [
                "Same time daily, 30–45 minutes — after lunch works best",
                "A defined space: their room with 4–5 pre-chosen quiet activities",
                "The rule: stay in the space, play quietly. That is the whole rule.",
            ]),
            ("Stock the quiet box", [
                "Rotate weekly: puzzles, coloring, books, stickers, blocks, audiobook + headphones",
                "Novelty matters — the same toys get loud; 'new' old toys stay quiet",
                "No screens — the point is independent, low-stimulation play",
            ]),
            ("Teach it gradually", [
                "Week 1: 15 minutes, you stay nearby",
                "Week 2: 25 minutes, check in once",
                "Week 3: 35–45 minutes solo — most kids get there",
                "A visual timer makes the end concrete — 'when the red is gone'",
            ]),
        ],
        "try": ["Pick the quiet-time spot today", "Stock the first quiet box", "Start with 15 minutes tomorrow"],
        "close": "Rest is a skill. Quiet time is the lesson.",
    },
    {
        "slug": "following-instructions", "emoji": "📋", "sort": 91,
        "title": "Following Instructions: The 3-Step Game",
        "excerpt": "Multi-step directions are the #1 school readiness skill. Train it with treasure hunts.",
        "intro": "School runs on multi-step instructions: 'Put your folder in the cubby, wash your hands, sit on the carpet.' Kids who cannot hold 3 steps struggle — whatever their intelligence.",
        "sections": [
            ("The training progression", [
                "1 step (age 3): 'Bring me the red ball.' — celebrate success",
                "2 steps (age 4): 'Bring the red ball and put it in the box.'",
                "3 steps (age 5): 'Bring the red ball, put it in the box, and clap twice.'",
                "Silly steps keep it fun — the sillier, the better remembered",
            ]),
            ("The treasure hunt method", [
                "Hide a treat; give 3-step directions to find it: 'Go to the kitchen, look under the table, check the blue cup.'",
                "Then THEY hide and direct YOU — giving instructions trains receiving them",
                "Our scavenger hunt printable is ready-made practice",
            ]),
            ("Everyday reps", [
                "Cooking: 'Pour, stir, taste' — real 3-step sequences",
                "Cleanup: 'Blocks in the bin, books on the shelf, cars in the garage'",
                "Getting ready: the morning chart IS instruction-following practice",
            ]),
        ],
        "try": ["Run a 3-step treasure hunt today", "Give only 2-step directions for 3 days", "Let them direct YOU once"],
        "close": "School is 3 steps at a time. Practice at home first.",
    },
    {
        "slug": "sleep-guide", "emoji": "😴", "sort": 92,
        "title": "The Sleep Guide: How Much, When, and Naps",
        "excerpt": "The numbers by age, the nap transition, and the 3 sleep killers hiding in your home.",
        "intro": "Sleep affects everything: mood, learning, immunity, growth. Most 3–6 year olds are slightly sleep-deprived — here are the targets and the fixes.",
        "sections": [
            ("How much they need", [
                "Age 3: 10–13 hours total (including naps)",
                "Age 4–5: 10–12 hours, naps fading",
                "Age 6: 9–12 hours, usually no nap",
                "If they cannot wake happily, they need more — the behavior is the test",
            ]),
            ("The nap transition (age 3–4)", [
                "Signs: takes forever to fall asleep at night, or bedtime pushes past 9",
                "Do not quit cold turkey — try quiet time instead (see our quiet-time guide)",
                "Early bedtime (7 PM) on no-nap days prevents the overtired spiral",
            ]),
            ("The 3 sleep killers", [
                "Screens within 1 hour of bed — the blue light delays melatonin",
                "Inconsistent bedtime — the brain cannot predict, so it cannot wind down",
                "Too-warm room — cool (65–68F) and dark wins",
            ]),
        ],
        "try": ["Set a fixed bedtime for 2 weeks and watch behavior", "Move screens 1 hour before bed", "Try quiet time on nap-refusal days"],
        "close": "Behavior problems are often sleep problems in disguise.",
    },
    {
        "slug": "eating-rainbow", "emoji": "🌈", "sort": 93,
        "title": "Eating the Rainbow: Nutrition Without Lectures",
        "excerpt": "Picky eaters do not need pressure — they need exposure, games, and time.",
        "intro": "Pressuring picky eaters backfires reliably. What works: repeated no-pressure exposure, playful framing, and involving them in the food.",
        "sections": [
            ("The rainbow game", [
                "'Can we eat every color today?' — red peppers, orange carrots, green broccoli, blueberries, purple cabbage",
                "Track colors on the fridge — kids chase the full set",
                "No forcing bites. The rule: it goes on the plate. That is all.",
            ]),
            ("Exposure math", [
                "It takes 10–15 exposures for a child to accept a new food — most parents quit at 3",
                "Exposure = seeing, touching, smelling — NOT eating. Licking counts as a win.",
                "Serve rejected foods alongside safe foods, no comment",
            ]),
            ("Power moves", [
                "Let them cook it — kids eat what they make (see our kitchen-helper guide)",
                "Grow it — a cherry tomato from THEIR plant gets eaten",
                "Dip everything: hummus, yogurt, peanut butter — dips are vegetable delivery systems",
                "You eat it happily. Modeling beats all strategies combined.",
            ]),
        ],
        "try": ["Start the rainbow chart this week", "Serve one rejected food with zero pressure", "Add one dip to dinner"],
        "close": "Division of labor: you decide WHAT, they decide HOW MUCH.",
    },
    {
        "slug": "outdoor-play", "emoji": "🌳", "sort": 94,
        "title": "Why 1 Hour Outside Changes Everything",
        "excerpt": "The research is overwhelming: outdoor play improves sleep, mood, eyesight, and immunity.",
        "intro": "Pediatricians now 'prescribe' outdoor time. One hour daily is the target — and it does not need to be a hike. The yard counts.",
        "sections": [
            ("What the hour does", [
                "Better sleep that night — daylight sets the body clock",
                "Better mood and fewer meltdowns — nature is a nervous-system reset",
                "Better eyesight — outdoor light protects against myopia",
                "Stronger immunity and bigger movement — climbing, running, digging",
            ]),
            ("Make it happen daily", [
                "Anchor it: right after lunch, or right after school — same slot daily",
                "Dress for the weather, not the wish — rain boots unlock rainy days",
                "The yard is enough: digging patch, ball, chalk, water",
            ]),
            ("What to do out there", [
                "Unstructured first: let them lead for 30 minutes",
                "Then one invitation: scavenger hunt, chalk obstacle course, bug safari",
                "Our nature scavenger hunt printable is ready to go",
            ]),
        ],
        "try": ["Anchor a daily outdoor slot this week", "Get rain boots if weather is the excuse", "Print the scavenger hunt"],
        "close": "There is no bad weather, only bad clothing. Go out.",
    },
    {
        "slug": "doctor-visits", "emoji": "🩺", "sort": 95,
        "title": "Doctor Visits Without Fear: The Pretend-Play Prep",
        "excerpt": "Fear comes from surprise. A $5 doctor kit and 3 play sessions remove it.",
        "intro": "Kids fear the doctor because it is unpredictable and involves discomfort. Pretend play makes it predictable — the single most effective fear reducer.",
        "sections": [
            ("The 3 play sessions (week before)", [
                "Session 1: THEY are the doctor, teddy is the patient — checkup, all fine",
                "Session 2: teddy needs a shot — 'a quick pinch, then a sticker!'",
                "Session 3: they are the patient, you are the doctor — practice opening wide, staying still",
            ]),
            ("Day-of tactics", [
                "Narrate honestly: 'There will be a quick pinch. It is okay to say ouch.'",
                "Never lie: 'It will not hurt' destroys trust for next time",
                "Bring the comfort object and a post-visit plan: 'After, we get smoothies.'",
                "Let them ask the doctor questions — control reduces fear",
            ]),
            ("After", [
                "Praise bravery specifically: 'You held still even though it pinched.'",
                "Play doctor again at home — processing through play",
            ]),
        ],
        "try": ["Get a play doctor kit", "Run session 1 this week", "Plan the post-visit treat in advance"],
        "close": "Predictable is safe. Rehearse the visit.",
    },
    {
        "slug": "sick-days", "emoji": "🤒", "sort": 96,
        "title": "Sick Day Survival: Rest, Fluids, and Low-Energy Fun",
        "excerpt": "The 3 jobs of a sick day, plus 10 couch-friendly activities that are not just TV.",
        "intro": "A sick day has 3 jobs: rest, fluids, comfort. Everything else is optional. Ten low-energy activities keep everyone sane.",
        "sections": [
            ("The 3 jobs", [
                "Rest: protect sleep — dark room, no 'catching up on shows' all day",
                "Fluids: water, broth, popsicles — offer every 30 minutes, small amounts",
                "Comfort: their blanket, their spot, your presence — medicine for the mood",
            ]),
            ("10 couch activities", [
                "Audiobook + coloring (the sick-day MVP)",
                "Sticker books — zero energy required",
                "Card games: War, Go Fish — playable horizontal",
                "Drawing prompts: 'Draw how your throat feels' (funny + expressive)",
                "Puzzles — the 24-piece kind",
                "Window bird-watching with a simple checklist",
                "Playdough — lap tray, minimal mess",
                "Video call grandparents — social without germs",
                "Sorting games: buttons by color in bed",
                "Build a blanket fort AROUND the couch — recovery headquarters",
            ]),
            ("When to call the doctor", [
                "Trust your gut — you know your child",
                "General guides: trouble breathing, dehydration signs, fever + rash, or 'just not right' for 24h",
            ]),
        ],
        "try": ["Stock a sick-day box: stickers, audiobook, popsicles", "Make the blanket fort once — they will ask again", "Save this list for the next fever"],
        "close": "Sick days are for healing. Lower the bar, raise the blankets.",
    },
]
